"""Frozen candidate catalog across families A–E.

Coverage numbers come from committed organic/pSEO fixtures and existing
engines. Live DSN is optional and never invents volumes. Snapshot as_of
is frozen — never wall-clock.
"""

from __future__ import annotations

from typing import Any

CATALOG_AS_OF = "2026-08-01"
CATALOG_ID = "traffic-frontier-catalog/2026-08-01"

# Existing published or proposed assets (organic demand graph + pSEO paths).
EXISTING_ASSETS: tuple[dict[str, Any], ...] = (
    {
        "url": "/reequilibrio-obras-publicas/",
        "kind": "service",
        "fingerprint": "quando cabe reequilíbrio e como estruturar um pleito defensável?",
    },
    {
        "url": "/aditivos-obras-publicas/",
        "kind": "service",
        "fingerprint": "como contar o limite de 25%/50% e o que documentar no aditivo?",
    },
    {
        "url": "/conteudos/sinapi-desonerado-nao-desonerado/",
        "kind": "editorial",
        "fingerprint": "qual base usar e como alinhar bdi e encargos?",
    },
    {
        "url": "/auditoria-orcamento-licitacao/",
        "kind": "service",
        "fingerprint": "participar, impugnar ou auditar a planilha antes da proposta?",
    },
    {
        "url": "/radar/edificacoes-publicas-sc/",
        "kind": "pseo_radar",
        "fingerprint": "radar de editais abertos de edificacao publica em <uf>",
    },
    {
        "url": "/metodologia-inteligencia/",
        "kind": "service",
        "fingerprint": "isso é normal no mercado público de obras?",
    },
    {
        "url": "/medicoes-glosas-obras-publicas/",
        "kind": "service",
        "fingerprint": "como contestar glosa e proteger o fluxo de caixa?",
    },
    {
        "url": "/acompanhamento-contratos-obras/",
        "kind": "service",
        "fingerprint": "quando vale consultoria de acompanhamento contratual vs equipe própria?",
    },
)


def _scope_uf(code: str, label: str) -> dict[str, Any]:
    return {"kind": "UF", "codes": [code], "label": label}


SCOPE_SC = _scope_uf("SC", "Santa Catarina")
SCOPE_BR = {"kind": "BR", "codes": ["BR"], "label": "nacional"}
PERIOD_24_26 = {"start": "2024-01-01", "end": "2026-07-01", "as_of": CATALOG_AS_OF}

SC_EDIFICACAO_COVERAGE = {
    "state": "success_with_data",
    "kind": "aggregate",
    "record_count": 24,
    "buyer_count": 9,
    "supplier_count": 12,
    "p25_value": 180000.0,
    "p50_value": 420000.0,
    "p75_value": 910000.0,
    "freshness_hours": 24,
    "stale": False,
    "complete_for_scope": True,
    "nacional_completo": False,
    "as_of": CATALOG_AS_OF,
    "sources": [
        "scripts/organic/fixtures/markets.json#market-edificacoes-publicas-sc",
        "pncp_supplier_contracts",
    ],
}

METHOD_COVERAGE = {
    "state": "success_with_data",
    "kind": "method",
    "record_count": 0,
    "freshness_hours": 0,
    "stale": False,
    "complete_for_scope": True,
    "nacional_completo": False,
    "as_of": CATALOG_AS_OF,
    "sources": [],
}


def _candidate(**kwargs: Any) -> dict[str, Any]:
    return dict(kwargs)


def load_catalog() -> list[dict[str, Any]]:
    """Return the frozen A–E candidate set (copies)."""
    return [dict(item) for item in CANDIDATES]


CANDIDATES: tuple[dict[str, Any], ...] = (
    _candidate(
        opportunity_id="tof-ticket-edificacao-sc",
        family="A",
        question=(
            "Qual o ticket típico (P25/mediana/P75) de contratos de edificação "
            "pública em Santa Catarina, e por que esse valor não é custo unitário?"
        ),
        visitor_job=(
            "Comparar o próprio contrato/proposta com uma referência de ticket "
            "integral no recorte SC, sem tratar o número como preço por m²."
        ),
        search_intent="informational",
        audience="diretor-construtora",
        funnel_stage="tofu",
        commercial_pain=(
            "Decisão de entrar ou precificar sem âncora de ticket leva a "
            "proposta irreal ou a recusa cega de contratos viáveis."
        ),
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "A leitura do recorte e dos limites é o serviço de inteligência, não um preço mágico.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="archetype × UF × período",
        coverage=SC_EDIFICACAO_COVERAGE,
        market_job={
            "present": True,
            "plausibility": 0.86,
            "text": "Quanto custa um contrato típico de edificação pública em SC?",
        },
        search_signal={
            "gsc_present": False,
            "impressions": 0,
            "clicks": 0,
            "position": 0,
            "related_queries": [
                "benchmark contratos obras públicas",
                "mediana valor contrato obra pública",
            ],
        },
        distinctive_edge=(
            "Agregado PNCP do recorte SC com P25/P50/P75 e distinção explícita "
            "valor_contratado ≠ custo unitário (value_semantics)."
        ),
        unknown=[
            "Custo unitário (R$/m²) — o dataset não tem área executada.",
            "Série nacional — nacional_completo é falso (#302).",
        ],
        factual_answer_outline=(
            "No recorte edificações-públicas × SC × 2024-01-01 a 2026-07-01 "
            "(n=24 contratos, 9 órgãos, 12 fornecedores, fonte pncp_supplier_contracts) "
            "o ticket integral nominal é P25 R$ 180 mil, mediana R$ 420 mil, "
            "P75 R$ 910 mil. Isso é valor do instrumento, não preço praticado por m² "
            "nem censo do Brasil."
        ),
        unique_insight=(
            "O P75 (~2,2× a mediana) no recorte SC já mostra cauda longa: "
            "usar a média como 'preço de mercado' enviesa proposta."
        ),
        unique_insight_key="ticket-vs-unit-cost-sc-edificacao",
        calculations={
            "n": 24,
            "p25_brl": 180000.0,
            "p50_brl": 420000.0,
            "p75_brl": 910000.0,
            "p75_over_p50": 2.167,
            "buyer_count": 9,
            "supplier_count": 12,
            "value_semantics": "valor_contratado integral nominal BRL",
        },
        limitations=[
            "Amostra regional SC; não é censo nacional.",
            "Valor integral do instrumento; sem deflação e sem unidade física.",
            "n=24 é suficiente para percentis do recorte, não para órgãos individuais.",
        ],
        prohibited_claims=[
            "Ticket nacional de obras públicas.",
            "Preço praticado por m² ou 'custo real' da obra.",
            "4,5 milhões de contratos como denominador desta página.",
            "Extra 1093 como universo Brasil.",
        ],
        suggested_visuals=[
            "Box-plot P25/mediana/P75 do recorte SC",
            "Nota de escopo geográfico (SC, não BR)",
        ],
        suggested_internal_links=[
            "/metodologia-inteligencia/",
            "/auditoria-orcamento-licitacao/",
            "/radar/edificacoes-publicas-sc/",
        ],
        suggested_cta="Ver metodologia e limites da inteligência de mercado",
        cta_connected=True,
        maintenance_owner="web-cfg-editorial + extra-cli public-read",
        refresh_policy="republicar só com novo snapshot as_of do mesmo recorte; nunca wall-clock",
        proposed_url="/respostas/ticket-tipico-edificacao-publica-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.78,
            "data_coverage_freshness": 0.84,
            "proprietary_differentiation": 0.82,
            "citability": 0.74,
            "time_to_publish": 0.88,
            "maintenance_cost": 0.32,
        },
    ),
    _candidate(
        opportunity_id="tof-data-base-reajuste-reequilibrio",
        family="B",
        question=(
            "Como a data-base e o índice declarado distinguem reajuste de "
            "reequilíbrio em contrato de obra pública — e o que o extrato "
            "público não prova sobre margem?"
        ),
        visitor_job=(
            "Decidir se o aniversário contratual autoriza reajuste automático "
            "ou se o caso pede revisão técnica da equação."
        ),
        search_intent="commercial",
        audience="gerente-contratos",
        funnel_stage="mofu",
        commercial_pain=(
            "Trocar reajuste por reequilíbrio (ou o inverso) queima prazo, "
            "documento e margem — e o extrato do PNCP quase nunca traz a data-base exata."
        ),
        offer_bridge={
            "service_slug": "reequilibrio-obras-publicas",
            "service_path": "/reequilibrio-obras-publicas/",
            "why": "O diagnóstico de data-base/índice é o primeiro filtro do pleito de reequilíbrio.",
        },
        geographic_scope={"kind": "method", "codes": [], "label": "método nacionalmente aplicável; sem censo BR"},
        temporal_scope={"start": None, "end": None, "as_of": CATALOG_AS_OF},
        grain="contrato × cláusula de reajuste × evento",
        coverage={
            **METHOD_COVERAGE,
            "sources": [
                "scripts/commercial/reajuste_14133/domain/data_base_exact.py",
                "scripts/organic/demand_graph.py#need-reequilibrio-pleito",
                "scripts/organic/fixtures/problem_service.json#prob-reequilibrio",
            ],
        },
        market_job={
            "present": True,
            "plausibility": 0.9,
            "text": "Reajuste ou reequilíbrio — como saber qual cabe agora?",
        },
        search_signal={
            "gsc_present": False,
            "impressions": 0,
            "clicks": 0,
            "position": 0,
            "related_queries": [
                "reajuste ou reequilíbrio obra pública",
                "reequilíbrio econômico financeiro obra pública",
                "data-base contrato público",
            ],
        },
        distinctive_edge=(
            "Engine Lei 14.133 já distingue data-base EXATA (cláusula/orçamento) "
            "de proxies (assinatura, publicação, início de execução) — "
            "mencionar 'data-base' no texto não satisfaz o critério."
        ),
        unknown=[
            "Frequência empírica de reajuste no recorte — sem série de eventos.",
            "Direito ao reequilíbrio do contrato concreto — exige dossiê.",
        ],
        factual_answer_outline=(
            "Reajuste em sentido estrito depende de índice declarado + data-base "
            "localizada na cláusula ou no orçamento de referência. Assinatura, "
            "publicação e início de execução NÃO contam como data-base exata "
            "(data_base_exact). Reequilíbrio exige álea extraordinária e nexo — "
            "o aniversário sozinho não autoriza o pleito. O extrato público "
            "raramente traz a cláusula completa."
        ),
        unique_insight=(
            "A menção da expressão 'data-base' no contrato é evidência insuficiente; "
            "o engine só aceita data ou competência na cláusula de reajuste ou no orçamento referenciado."
        ),
        unique_insight_key="data-base-exact-vs-proxy",
        calculations={
            "satisfying_states": [
                "EXACT_DATE_IN_REAJUSTE_CLAUSE",
                "EXACT_COMPETENCE_IN_REAJUSTE_CLAUSE",
                "EXACT_DATE_IN_REFERENCED_BUDGET",
                "COMPETENCE_IN_BUDGET_SPREADSHEET",
            ],
            "never_exact": ["PROXY_SIGNATURE_OR_START", "GENERIC_RULE_WITHOUT_DATE"],
        },
        limitations=[
            "Método normativo + engine; não é frequência observada de reajustes.",
            "Não conclui direito a reequilíbrio sem o contrato concreto.",
            "Não é censo nacional de cláusulas.",
        ],
        prohibited_claims=[
            "Todo contrato com aniversário tem direito a reajuste.",
            "Aniversário prova reequilíbrio.",
            "Margem da construtora inferida do extrato PNCP.",
            "Estatística nacional de reajustes.",
        ],
        suggested_visuals=[
            "Fluxo: índice + data-base exata → reajuste; álea + nexo → reequilíbrio",
            "Tabela do que NÃO conta como data-base",
        ],
        suggested_internal_links=[
            "/reequilibrio-obras-publicas/",
            "/conteudos/reequilibrio-economico-financeiro-obra-publica/",
            "/aditivos-obras-publicas/",
        ],
        suggested_cta="Analisar viabilidade de reequilíbrio",
        cta_connected=True,
        maintenance_owner="commercial/reajuste_14133 + web-cfg-editorial",
        refresh_policy="atualizar se o critério data_base_exact mudar; sem série empírica periódica",
        proposed_url="/respostas/data-base-reajuste-ou-reequilibrio/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.92,
            "data_coverage_freshness": 0.8,
            "proprietary_differentiation": 0.9,
            "citability": 0.72,
            "time_to_publish": 0.86,
            "maintenance_cost": 0.28,
        },
    ),
    _candidate(
        opportunity_id="tof-eventos-contratuais-revisao",
        family="D",
        question=(
            "Quais eventos contratuais (aditivo, atraso, glosa, alteração) "
            "merecem revisão técnica da equação — e o que o extrato público "
            "não permite concluir?"
        ),
        visitor_job=(
            "Filtrar ruído do extrato e saber quando chamar diagnóstico antes de o prejuízo virar fato consumado."
        ),
        search_intent="commercial",
        audience="engenheiro-contratos",
        funnel_stage="bofu",
        commercial_pain=(
            "Aditivo, glosa e atraso chegam como rotina administrativa; "
            "a margem some sem que ninguém tenha aberto um dossiê."
        ),
        offer_bridge={
            "service_slug": "acompanhamento-contratos-obras",
            "service_path": "/acompanhamento-contratos-obras/",
            "why": "Evento público é gatilho de diagnóstico, não prova de irregularidade.",
        },
        geographic_scope={"kind": "method", "codes": [], "label": "método; sem série nacional de eventos"},
        temporal_scope={"start": None, "end": None, "as_of": CATALOG_AS_OF},
        grain="evento contratual × contrato",
        coverage={
            **METHOD_COVERAGE,
            "sources": [
                "scripts/organic/demand_graph.py#need-aditivo-limite",
                "scripts/organic/demand_graph.py#need-medicao-glosa",
                "scripts/organic/demand_graph.py#need-atraso-prorrogacao",
                "scripts/ops/contract_market_intelligence.py",
            ],
        },
        market_job={
            "present": True,
            "plausibility": 0.88,
            "text": "Quando um aditivo ou glosa pede revisão técnica de verdade?",
        },
        search_signal={
            "gsc_present": False,
            "impressions": 0,
            "clicks": 0,
            "position": 0,
            "related_queries": [
                "aditivos obra pública",
                "glosa de medição obra pública",
                "prorrogação prazo obra pública",
            ],
        },
        distinctive_edge=(
            "Grafo de demanda CONFENGE liga aditivo, glosa e atraso a serviços "
            "distintos; CMI recusa win-rate/HHI sem denominador — o mesmo rigor "
            "vale para não inferir ilegalidade de um extrato."
        ),
        unknown=[
            "Frequência e valor de aditivos no recorte (issue #415, HOLD).",
            "Pagamentos reais (valor_pago) — PNCP expõe valor_contratado.",
        ],
        factual_answer_outline=(
            "Eventos que merecem revisão: aditivo que se aproxima de 25%/50%, "
            "glosa de medição, atraso imputável à Administração, alteração de "
            "objeto ou prazo, índice/data-base ausentes. O extrato público "
            "documenta que o evento existiu; não documenta culpa, sobrepreço "
            "nem direito automático. valor_contratado não é valor_pago."
        ),
        unique_insight=(
            "O mesmo extrato alimenta três serviços distintos (aditivo, glosa, "
            "prazo). Tratar tudo como 'problema de contrato' é o erro que a "
            "página corrige."
        ),
        unique_insight_key="evento-publico-nao-e-prova",
        calculations={
            "event_triggers": [
                "aditivo_proximo_limite",
                "glosa_medicao",
                "atraso_administracao",
                "alteracao_objeto_prazo",
                "data_base_ausente",
            ],
            "value_semantics_ref": "scripts.lib.value_semantics.ValorSemantica",
        },
        limitations=[
            "Checklist de gatilho; não é série empírica de eventos.",
            "Não conclui ilegalidade nem êxito de pleito.",
        ],
        prohibited_claims=[
            "Aditivo acima de 25% é ilegal.",
            "Glosa no extrato prova má-fé do órgão.",
            "Atraso sempre gera reequilíbrio.",
            "Série nacional de aditivos.",
        ],
        suggested_visuals=[
            "Matriz evento → pergunta técnica → serviço CONFENGE",
            "O que o extrato prova vs. o que exige dossiê",
        ],
        suggested_internal_links=[
            "/aditivos-obras-publicas/",
            "/medicoes-glosas-obras-publicas/",
            "/atrasos-prorrogacao-obras-publicas/",
            "/reequilibrio-obras-publicas/",
            "/acompanhamento-contratos-obras/",
        ],
        suggested_cta="Diagnosticar gestão contratual B2G",
        cta_connected=True,
        maintenance_owner="web-cfg-editorial + organic demand graph",
        refresh_policy="atualizar se o grafo de demanda ou value_semantics mudar",
        proposed_url="/respostas/eventos-contratuais-que-pedem-revisao/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.9,
            "data_coverage_freshness": 0.76,
            "proprietary_differentiation": 0.84,
            "citability": 0.68,
            "time_to_publish": 0.84,
            "maintenance_cost": 0.3,
        },
    ),
    _candidate(
        opportunity_id="tof-orgaos-atividade-edificacao-sc",
        family="E",
        question=(
            "Quais órgãos concentram contratos de edificação pública em "
            "Santa Catarina no período 2024–2026, e o que essa concentração "
            "não autoriza afirmar?"
        ),
        visitor_job=(
            "Priorizar prospecção e leitura de mercado no recorte SC sem tratar 9 órgãos como o mercado brasileiro."
        ),
        search_intent="informational",
        audience="diretor-construtora",
        funnel_stage="tofu",
        commercial_pain="Prospecção genérica em órgão sem volume no recorte.",
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "Atividade do recorte é topo de funil da inteligência, não ranking nacional.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="órgão × archetype × UF × período",
        coverage=SC_EDIFICACAO_COVERAGE,
        market_job={
            "present": True,
            "plausibility": 0.72,
            "text": "Quais órgãos de SC mais contratam edificação pública?",
        },
        search_signal={
            "gsc_present": False,
            "impressions": 0,
            "clicks": 0,
            "position": 0,
            "related_queries": ["órgãos que mais licitam obras SC"],
        },
        distinctive_edge="9 órgãos distintos no recorte SC de 24 contratos; concentração do recorte, não HHI nacional.",
        unknown=["Identidade nominada de cada órgão no fixture público (apenas a contagem)."],
        factual_answer_outline=(
            "O recorte edificações-públicas × SC tem 9 órgãos compradores e "
            "12 fornecedores em 24 contratos. Isso descreve pulverização relativa "
            "do recorte; não é HHI nacional nem ranking de capacidade."
        ),
        unique_insight="9 órgãos / 24 contratos ⇒ média <3 contratos por órgão: a 'concentração' do recorte é baixa.",
        unique_insight_key="buyer-spread-sc-edificacao",
        calculations={
            "buyer_count": 9,
            "supplier_count": 12,
            "n": 24,
            "contracts_per_buyer_mean": 2.667,
        },
        limitations=[
            "Contagem do recorte; nomes de órgãos não estão no fixture público.",
            "Não é market share nacional.",
        ],
        prohibited_claims=[
            "HHI ou market share Brasil.",
            "Órgão X é o maior contratante do país.",
            "Contagem de contratos = capacidade do fornecedor.",
        ],
        suggested_visuals=["Barras de contratos por órgão quando a série nominada existir"],
        suggested_internal_links=["/metodologia-inteligencia/", "/respostas/ticket-tipico-edificacao-publica-sc/"],
        suggested_cta="Ver metodologia e limites da inteligência de mercado",
        cta_connected=True,
        maintenance_owner="web-cfg-editorial",
        refresh_policy="mesmo snapshot do ticket SC",
        proposed_url="/respostas/orgaos-edificacao-publica-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.62,
            "data_coverage_freshness": 0.7,
            "proprietary_differentiation": 0.64,
            "citability": 0.58,
            "time_to_publish": 0.7,
            "maintenance_cost": 0.4,
        },
    ),
    _candidate(
        opportunity_id="tof-modalidade-regime-edificacao-sc",
        family="C",
        question=(
            "Quais modalidades e regimes predominam em editais de edificação "
            "pública em Santa Catarina, e o que isso muda na preparação da proposta?"
        ),
        visitor_job="Ajustar esforço de proposta ao regime/modalidade do recorte.",
        search_intent="informational",
        audience="licitacoes",
        funnel_stage="mofu",
        commercial_pain="Preparar proposta no regime errado destrói BDI e prazo.",
        offer_bridge={
            "service_slug": "bid-room-licitacoes-obras",
            "service_path": "/bid-room-licitacoes-obras/",
            "why": "Modalidade do recorte informa o bid room; não promete vitória.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="modalidade × regime × archetype × UF",
        coverage={
            "state": "partial",
            "kind": "aggregate",
            "record_count": 24,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/organic/fixtures/markets.json"],
        },
        market_job={
            "present": True,
            "plausibility": 0.7,
            "text": "Qual modalidade predomina em obras de edificação em SC?",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="Recorte SC existe; breakdown modalidade/regime não está no fixture.",
        unknown=["Contagens por modalidade e regime no recorte."],
        factual_answer_outline="O recorte SC tem 24 contratos, mas o fixture não quebra modalidade/regime.",
        unique_insight="Sem o breakdown, qualquer 'pregão predomina em SC' seria invenção.",
        unique_insight_key="modalidade-sc-missing-breakdown",
        calculations={},
        limitations=["Cobertura incompleta para a pergunta."],
        prohibited_claims=["Modalidade predominante no Brasil.", "Promessa de vitória por modalidade."],
        suggested_visuals=["Barras modalidade × n quando a série existir"],
        suggested_internal_links=["/bid-room-licitacoes-obras/", "/auditoria-orcamento-licitacao/"],
        suggested_cta="Avaliar se a licitação cabe no perfil da construtora",
        cta_connected=True,
        maintenance_owner="pseo + public-read",
        refresh_policy="HOLD até existir breakdown modalidade/regime no recorte",
        proposed_url="/respostas/modalidade-edificacao-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.7,
            "data_coverage_freshness": 0.28,
            "proprietary_differentiation": 0.5,
            "citability": 0.4,
            "time_to_publish": 0.25,
            "maintenance_cost": 0.55,
        },
    ),
    _candidate(
        opportunity_id="tof-faixas-aditivo-recorte-sc",
        family="A",
        question=(
            "Quais faixas de aditivo (% sobre o valor contratado) aparecem em obras de edificação em Santa Catarina?"
        ),
        visitor_job="Comparar o próprio aditivo com a distribuição do recorte.",
        search_intent="informational",
        audience="engenheiro-contratos",
        funnel_stage="mofu",
        commercial_pain="Aditivo sem âncora de faixa vira chute ou omissão.",
        offer_bridge={
            "service_slug": "aditivos-obras-publicas",
            "service_path": "/aditivos-obras-publicas/",
            "why": "Faixa empírica do recorte ancora a revisão de aditivo.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="contrato × aditivo × UF",
        coverage={
            "state": "pending",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/ops/contract_market_intelligence.py", "extra-cli#415"],
        },
        market_job={
            "present": True,
            "plausibility": 0.8,
            "text": "Qual o percentual típico de aditivo em obra pública em SC?",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="Pergunta é o núcleo de #415; peer groups ainda não fecham.",
        unknown=["Série de aditivos com denominador comparável."],
        factual_answer_outline="Sem peer group fail-closed (#415) não há faixa publicável.",
        unique_insight="Comparação ruim é pior que ausência — HOLD é o estado honesto.",
        unique_insight_key="aditivo-faixa-hold-415",
        calculations={},
        limitations=["Issue #415 aberta; sem métrica reproduzível."],
        prohibited_claims=["Faixa nacional de aditivos.", "Aditivo típico de 25%."],
        suggested_visuals=["Histograma de % quando #415 fechar no recorte"],
        suggested_internal_links=["/aditivos-obras-publicas/", "/ferramentas/limite-acrescimos-supressoes/"],
        suggested_cta="Revisar estratégia de aditivo",
        cta_connected=True,
        maintenance_owner="comparables #415",
        refresh_policy="HOLD_FOR_DATA até #415 entregar o recorte",
        proposed_url="/respostas/faixas-aditivo-edificacao-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.84,
            "data_coverage_freshness": 0.12,
            "proprietary_differentiation": 0.7,
            "citability": 0.55,
            "time_to_publish": 0.15,
            "maintenance_cost": 0.7,
        },
    ),
    _candidate(
        opportunity_id="tof-ticket-nacional-br",
        family="A",
        question="Qual o ticket típico de contratos de obras públicas no Brasil?",
        visitor_job="Obter uma referência nacional de preço contratual.",
        search_intent="informational",
        audience="diretor-construtora",
        funnel_stage="tofu",
        commercial_pain="Busca por âncora nacional para precificar.",
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "A recusa honesta do censo nacional é o serviço.",
        },
        geographic_scope=SCOPE_BR,
        temporal_scope=PERIOD_24_26,
        grain="archetype × BR × período",
        coverage={
            "state": "blocked",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/national_contract_truth", "extra-cli#302"],
        },
        market_job={
            "present": True,
            "plausibility": 0.75,
            "text": "Ticket típico de obra pública no Brasil",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="Claim gate public-read recusa nacional_completo.",
        unknown=["Denominador nacional de órgãos publicantes fechado (#302)."],
        factual_answer_outline="nacional_completo é falso; nenhum ticket BR é publicável.",
        unique_insight="A resposta útil hoje é o recorte SC, não o Brasil.",
        unique_insight_key="ticket-br-blocked-302",
        calculations={},
        limitations=["#302 aberto; Extra 1093 nunca é denominador."],
        prohibited_claims=["Ticket nacional.", "Censo Brasil a partir do recorte SC."],
        suggested_visuals=[],
        suggested_internal_links=["/respostas/ticket-tipico-edificacao-publica-sc/"],
        suggested_cta="Ver metodologia e limites da inteligência de mercado",
        cta_connected=True,
        maintenance_owner="national_contract_truth",
        refresh_policy="HOLD até nacional_completo",
        proposed_url="/respostas/ticket-obras-publicas-brasil/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=True,
        nacional_completo=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.7,
            "data_coverage_freshness": 0.05,
            "proprietary_differentiation": 0.4,
            "citability": 0.3,
            "time_to_publish": 0.05,
            "maintenance_cost": 0.85,
        },
    ),
    _candidate(
        opportunity_id="tof-custo-unitario-m2",
        family="A",
        question="Qual o custo por m² de edificação pública em Santa Catarina?",
        visitor_job="Obter R$/m² para orçar ou auditar planilha.",
        search_intent="informational",
        audience="orcamentista",
        funnel_stage="mofu",
        commercial_pain="Planilha sem âncora unitária.",
        offer_bridge={
            "service_slug": "auditoria-orcamento-licitacao",
            "service_path": "/auditoria-orcamento-licitacao/",
            "why": "Custo unitário exige composição, não ticket contratual.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="unidade física × tipologia × UF",
        coverage={
            "state": "blocked",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["docs/contracts/public-read-research-flagship-v1.json"],
        },
        market_job={
            "present": True,
            "plausibility": 0.82,
            "text": "Custo por m² de obra pública SC",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="O contrato public-read proíbe explicitamente preço por m² a partir do ticket.",
        unknown=["Área executada e composição unitária."],
        factual_answer_outline="Ticket integral não se divide em m² sem área; a célula seria UNKNOWN.",
        unique_insight="A recusa é o insight: valor_contratado ≠ custo unitário.",
        unique_insight_key="unit-cost-unknown",
        calculations={},
        limitations=["Sem unidade física no dataset de contratos."],
        prohibited_claims=["R$/m² derivado do ticket.", "Preço praticado nacional."],
        suggested_visuals=[],
        suggested_internal_links=["/auditoria-orcamento-licitacao/", "/respostas/ticket-tipico-edificacao-publica-sc/"],
        suggested_cta="Auditar orçamento e BDI do edital",
        cta_connected=True,
        maintenance_owner="public-read value semantics",
        refresh_policy="HOLD até existir unidade física comparável (#415)",
        proposed_url="/respostas/custo-m2-edificacao-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.8,
            "data_coverage_freshness": 0.08,
            "proprietary_differentiation": 0.55,
            "citability": 0.35,
            "time_to_publish": 0.1,
            "maintenance_cost": 0.8,
        },
    ),
    _candidate(
        opportunity_id="tof-concentracao-fornecedores-nacional",
        family="E",
        question="Qual a concentração de fornecedores de obras públicas no Brasil?",
        visitor_job="Medir HHI / market share nacional de construtoras.",
        search_intent="informational",
        audience="diretor-construtora",
        funnel_stage="tofu",
        commercial_pain="Ler competitividade do mercado nacional.",
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "CMI recusa HHI sem denominador comum.",
        },
        geographic_scope=SCOPE_BR,
        temporal_scope=PERIOD_24_26,
        grain="fornecedor × BR",
        coverage={
            "state": "blocked",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/ops/contract_market_intelligence.py"],
        },
        market_job={
            "present": True,
            "plausibility": 0.55,
            "text": "Concentração de mercado de obras públicas Brasil",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="CMI: market share / HHI sem denominador defensável = NOT_COMPUTABLE.",
        unknown=["Universo fechado de participantes."],
        factual_answer_outline="Sem denominador comum, HHI nacional é NOT_COMPUTABLE.",
        unique_insight="12 fornecedores no recorte SC não são o mercado Brasil.",
        unique_insight_key="hhi-br-not-computable",
        calculations={},
        limitations=["NOT_COMPUTABLE por contrato CMI."],
        prohibited_claims=["HHI nacional.", "Market share a partir do recorte SC."],
        suggested_visuals=[],
        suggested_internal_links=["/metodologia-inteligencia/"],
        suggested_cta="Ver metodologia e limites da inteligência de mercado",
        cta_connected=True,
        maintenance_owner="contract_market_intelligence",
        refresh_policy="HOLD",
        proposed_url="/respostas/concentracao-fornecedores-obras-brasil/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=True,
        nacional_completo=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.45,
            "data_coverage_freshness": 0.05,
            "proprietary_differentiation": 0.4,
            "citability": 0.25,
            "time_to_publish": 0.05,
            "maintenance_cost": 0.9,
        },
    ),
    _candidate(
        opportunity_id="tof-win-rate-editais-aec",
        family="C",
        question="Qual a taxa de vitória típica em editais de engenharia e obras?",
        visitor_job="Estimar probabilidade de ganhar um certame AEC.",
        search_intent="commercial",
        audience="licitacoes",
        funnel_stage="mofu",
        commercial_pain="Decidir participar com base em 'win rate de mercado'.",
        offer_bridge={
            "service_slug": "bid-room-licitacoes-obras",
            "service_path": "/bid-room-licitacoes-obras/",
            "why": "Sem denominador de propostas, win-rate é NOT_COMPUTABLE.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="proposta × certame",
        coverage={
            "state": "blocked",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/ops/contract_market_intelligence.py"],
        },
        market_job={
            "present": True,
            "plausibility": 0.6,
            "text": "Win rate de licitação de obras",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="CMI: win rate without proposal denominator → NOT_COMPUTABLE.",
        unknown=["Denominador de propostas por certame."],
        factual_answer_outline="Contrato homologado sem lista de propostas não gera win-rate.",
        unique_insight="Vitória observada ≠ taxa de vitória.",
        unique_insight_key="win-rate-not-computable",
        calculations={},
        limitations=["NOT_COMPUTABLE."],
        prohibited_claims=["Win-rate de mercado.", "Promessa de vitória."],
        suggested_visuals=[],
        suggested_internal_links=["/bid-room-licitacoes-obras/", "/diagnostico-pre-licitacao/"],
        suggested_cta="Avaliar se a licitação cabe no perfil da construtora",
        cta_connected=True,
        maintenance_owner="contract_market_intelligence",
        refresh_policy="HOLD",
        proposed_url="/respostas/win-rate-editais-obras/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.55,
            "data_coverage_freshness": 0.05,
            "proprietary_differentiation": 0.35,
            "citability": 0.2,
            "time_to_publish": 0.05,
            "maintenance_cost": 0.9,
        },
    ),
    _candidate(
        opportunity_id="tof-frequencia-empirica-reajuste",
        family="B",
        question=(
            "Com que frequência contratos de obra pública no recorte coberto registram reajuste documentalmente?"
        ),
        visitor_job="Saber se 'todo mundo reajusta' é fato ou lenda.",
        search_intent="informational",
        audience="gerente-contratos",
        funnel_stage="mofu",
        commercial_pain="Decidir rotina de reajuste com base em anedota.",
        offer_bridge={
            "service_slug": "reequilibrio-obras-publicas",
            "service_path": "/reequilibrio-obras-publicas/",
            "why": "Frequência empírica exigiria série de eventos; o método já é publicável.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="evento de reajuste × contrato × UF",
        coverage={
            "state": "pending",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/commercial/reajuste_14133"],
        },
        market_job={
            "present": True,
            "plausibility": 0.65,
            "text": "Quantos contratos de obra são reajustados por ano?",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="Engine classifica elegibilidade; não publica frequência.",
        unknown=["Série de eventos de reajuste no recorte."],
        factual_answer_outline="Sem série de eventos, qualquer % seria inventado.",
        unique_insight="O método (data-base exata) está READY; a frequência não.",
        unique_insight_key="reajuste-freq-hold",
        calculations={},
        limitations=["Sem série de eventos."],
        prohibited_claims=["X% dos contratos brasileiros são reajustados."],
        suggested_visuals=[],
        suggested_internal_links=["/respostas/data-base-reajuste-ou-reequilibrio/"],
        suggested_cta="Analisar viabilidade de reequilíbrio",
        cta_connected=True,
        maintenance_owner="reajuste_14133",
        refresh_policy="HOLD",
        proposed_url="/respostas/frequencia-reajuste-obras-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.6,
            "data_coverage_freshness": 0.1,
            "proprietary_differentiation": 0.55,
            "citability": 0.35,
            "time_to_publish": 0.12,
            "maintenance_cost": 0.75,
        },
    ),
    _candidate(
        opportunity_id="tof-serie-pagamentos-glosas",
        family="D",
        question="Qual a série de pagamentos e glosas em contratos de obra pública em SC?",
        visitor_job="Ver quanto foi pago versus glosado no recorte.",
        search_intent="informational",
        audience="engenheiro-obra",
        funnel_stage="mofu",
        commercial_pain="Fluxo de caixa sem âncora de glosa típica.",
        offer_bridge={
            "service_slug": "medicoes-glosas-obras-publicas",
            "service_path": "/medicoes-glosas-obras-publicas/",
            "why": "valor_pago não está no extrato PNCP de forma confiável.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope=PERIOD_24_26,
        grain="pagamento × medição × contrato",
        coverage={
            "state": "blocked",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/lib/value_semantics.py"],
        },
        market_job={
            "present": True,
            "plausibility": 0.58,
            "text": "Quanto se glosa em obra pública?",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="ValorSemantica.PAGO ≠ CONTRATADO; PNCP não entrega o pago.",
        unknown=["Série de empenhos/pagamentos ligada ao contrato."],
        factual_answer_outline="Sem valor_pago ligado, a série é UNKNOWN.",
        unique_insight="Tratar valor_contratado como pago é o erro que o contrato CMI recusa.",
        unique_insight_key="pago-vs-contratado",
        calculations={},
        limitations=["Fonte de pagamento não está no recorte publicável."],
        prohibited_claims=["Percentual nacional de glosa.", "Valor contratado = valor pago."],
        suggested_visuals=[],
        suggested_internal_links=["/medicoes-glosas-obras-publicas/"],
        suggested_cta="Revisar medição e glosa",
        cta_connected=True,
        maintenance_owner="value_semantics",
        refresh_policy="HOLD",
        proposed_url="/respostas/pagamentos-glosas-obras-sc/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.72,
            "data_coverage_freshness": 0.08,
            "proprietary_differentiation": 0.5,
            "citability": 0.3,
            "time_to_publish": 0.1,
            "maintenance_cost": 0.8,
        },
    ),
    _candidate(
        opportunity_id="tof-prazos-editais-aec-sul",
        family="C",
        question="Quais prazos típicos entre publicação e disputa em editais AEC no Sul?",
        visitor_job="Saber se dá tempo de montar proposta no recorte Sul.",
        search_intent="informational",
        audience="licitacoes",
        funnel_stage="mofu",
        commercial_pain="Perder certame por prazo curto sem ter medido o recorte.",
        offer_bridge={
            "service_slug": "bid-room-licitacoes-obras",
            "service_path": "/bid-room-licitacoes-obras/",
            "why": "Prazo do recorte informa o bid room.",
        },
        geographic_scope={"kind": "regiao", "codes": ["SC", "PR", "RS"], "label": "Sul"},
        temporal_scope=PERIOD_24_26,
        grain="edital × prazo × UF",
        coverage={
            "state": "pending",
            "kind": "aggregate",
            "record_count": 4,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["scripts/organic/fixtures/opportunities.json"],
        },
        market_job={
            "present": True,
            "plausibility": 0.6,
            "text": "Prazo típico de edital de obra no Sul",
        },
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="Radar SC tem 4 abertas — insuficiente para prazo típico do Sul.",
        unknown=["Datas de publicação e disputa no recorte Sul."],
        factual_answer_outline="n=4 abertas em SC não gera prazo típico de três UFs.",
        unique_insight="Amostra fina; Sul ≠ SC.",
        unique_insight_key="prazo-sul-thin",
        calculations={"open_n_sc": 4},
        limitations=["Amostra < 8; recorte Sul sem série."],
        prohibited_claims=["Prazo típico nacional.", "Sul a partir só de SC."],
        suggested_visuals=[],
        suggested_internal_links=["/bid-room-licitacoes-obras/", "/radar/"],
        suggested_cta="Avaliar se a licitação cabe no perfil da construtora",
        cta_connected=True,
        maintenance_owner="pseo radar",
        refresh_policy="HOLD",
        proposed_url="/respostas/prazos-editais-aec-sul/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        allow_national_language_in_prohibition=True,
        components={
            "commercial_pain_ticket": 0.58,
            "data_coverage_freshness": 0.18,
            "proprietary_differentiation": 0.4,
            "citability": 0.3,
            "time_to_publish": 0.2,
            "maintenance_cost": 0.65,
        },
    ),
    # --- REJECT fixtures (adversarial catalog members) ---
    _candidate(
        opportunity_id="tof-generic-o-que-e-licitacao",
        family="C",
        question="O que é licitação pública?",
        visitor_job="Entender o conceito de licitação.",
        search_intent="informational",
        audience="estudante",
        funnel_stage="tofu",
        commercial_pain="Nenhuma dor econômica de contratante AEC.",
        offer_bridge={
            "service_slug": "bid-room-licitacoes-obras",
            "service_path": "/bid-room-licitacoes-obras/",
            "why": "CTA forçada em pergunta genérica.",
        },
        geographic_scope={"kind": "method", "codes": [], "label": "genérico"},
        temporal_scope={"start": None, "end": None, "as_of": CATALOG_AS_OF},
        grain="n/a",
        coverage={**METHOD_COVERAGE, "complete_for_scope": True},
        market_job={"present": False, "plausibility": 0.1, "text": ""},
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="",
        unknown=[],
        factual_answer_outline="Definição commodity de licitação.",
        unique_insight="",
        unique_insight_key="",
        calculations={},
        limitations=["Sem edge proprietário."],
        prohibited_claims=["Qualquer claim factual de mercado."],
        suggested_visuals=[],
        suggested_internal_links=[],
        suggested_cta="Falar com a CONFENGE",
        cta_connected=False,
        maintenance_owner="none",
        refresh_policy="n/a",
        proposed_url="/respostas/o-que-e-licitacao/",
        existing_url=None,
        independent_utility=False,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=True,
        unsupported_legal_claim=False,
        claims_national=False,
        components={
            "commercial_pain_ticket": 0.1,
            "data_coverage_freshness": 0.5,
            "proprietary_differentiation": 0.05,
            "citability": 0.1,
            "time_to_publish": 0.9,
            "maintenance_cost": 0.1,
        },
    ),
    _candidate(
        opportunity_id="tof-ticket-edificacao-pr-clone",
        family="A",
        question=(
            "Qual o ticket típico (P25/mediana/P75) de contratos de edificação "
            "pública no Paraná, e por que esse valor não é custo unitário?"
        ),
        visitor_job="Igual ao de SC, trocando a UF.",
        search_intent="informational",
        audience="diretor-construtora",
        funnel_stage="tofu",
        commercial_pain="Mesma dor do item SC.",
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "Clone geográfico.",
        },
        geographic_scope=_scope_uf("PR", "Paraná"),
        temporal_scope=PERIOD_24_26,
        grain="archetype × UF × período",
        coverage={
            "state": "success_with_data",
            "kind": "aggregate",
            "record_count": 24,
            "stale": False,
            "complete_for_scope": True,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": ["clone"],
        },
        market_job={"present": True, "plausibility": 0.86, "text": "ticket PR"},
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="",
        unknown=[],
        factual_answer_outline="Mesma pergunta do recorte SC com UF trocada.",
        unique_insight="",
        unique_insight_key="ticket-vs-unit-cost-sc-edificacao",
        clone_of="tof-ticket-edificacao-sc",
        calculations={},
        limitations=["Clone de UF."],
        prohibited_claims=["Doorway por UF."],
        suggested_visuals=[],
        suggested_internal_links=[],
        suggested_cta="Ver metodologia e limites da inteligência de mercado",
        cta_connected=True,
        maintenance_owner="none",
        refresh_policy="n/a",
        proposed_url="/respostas/ticket-tipico-edificacao-publica-pr/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=True,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        components={
            "commercial_pain_ticket": 0.78,
            "data_coverage_freshness": 0.84,
            "proprietary_differentiation": 0.2,
            "citability": 0.4,
            "time_to_publish": 0.88,
            "maintenance_cost": 0.32,
        },
    ),
    _candidate(
        opportunity_id="tof-nacional-4m5-contratos",
        family="E",
        question="O que os 4,5 milhões de contratos públicos do Brasil revelam sobre obras?",
        visitor_job="Obter um panorama nacional impressionante.",
        search_intent="informational",
        audience="imprensa",
        funnel_stage="tofu",
        commercial_pain="Nenhuma — vanity metric.",
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "CTA desconectada de um claim falso.",
        },
        geographic_scope=SCOPE_BR,
        temporal_scope=PERIOD_24_26,
        grain="BR",
        coverage={
            "state": "blocked",
            "kind": "aggregate",
            "record_count": 0,
            "stale": False,
            "complete_for_scope": False,
            "nacional_completo": False,
            "as_of": CATALOG_AS_OF,
            "sources": [],
        },
        market_job={"present": True, "plausibility": 0.4, "text": "panorama nacional de contratos"},
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="",
        unknown=["Denominador nacional."],
        factual_answer_outline="O número 4,5 milhões não é um denominador fechado deste recorte.",
        unique_insight="",
        unique_insight_key="",
        calculations={},
        limitations=["Claim nacional sem cobertura."],
        prohibited_claims=["4,5 milhões como censo.", "Extra 1093 = Brasil."],
        suggested_visuals=[],
        suggested_internal_links=[],
        suggested_cta="Falar com a CONFENGE",
        cta_connected=False,
        maintenance_owner="none",
        refresh_policy="n/a",
        proposed_url="/respostas/45-milhoes-contratos-brasil/",
        existing_url=None,
        independent_utility=False,
        method_reproducible=False,
        is_doorway=False,
        generic_no_edge=True,
        unsupported_legal_claim=False,
        unsupported_economic_claim=True,
        claims_national=True,
        nacional_completo=False,
        components={
            "commercial_pain_ticket": 0.2,
            "data_coverage_freshness": 0.0,
            "proprietary_differentiation": 0.1,
            "citability": 0.1,
            "time_to_publish": 0.1,
            "maintenance_cost": 0.9,
        },
    ),
    _candidate(
        opportunity_id="tof-aditivo-25-e-ilegal",
        family="D",
        question="Por que todo aditivo acima de 25% em obra pública é ilegal?",
        visitor_job="Confirmar uma tese jurídica pronta.",
        search_intent="informational",
        audience="advogado",
        funnel_stage="mofu",
        commercial_pain="Medo de aditivo irregular.",
        offer_bridge={
            "service_slug": "aditivos-obras-publicas",
            "service_path": "/aditivos-obras-publicas/",
            "why": "Serviço existe, mas a pergunta já afirma o ilícito.",
        },
        geographic_scope={"kind": "method", "codes": [], "label": "jurídico"},
        temporal_scope={"start": None, "end": None, "as_of": CATALOG_AS_OF},
        grain="n/a",
        coverage={**METHOD_COVERAGE},
        market_job={"present": True, "plausibility": 0.5, "text": "aditivo 25% ilegal"},
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="",
        unknown=["O caso concreto."],
        factual_answer_outline="A premissa é falsa: o limite não torna o ato automaticamente ilegal.",
        unique_insight="",
        unique_insight_key="",
        calculations={},
        limitations=["Pergunta carrega claim jurídico."],
        prohibited_claims=["Aditivo >25% é ilegal."],
        suggested_visuals=[],
        suggested_internal_links=["/aditivos-obras-publicas/"],
        suggested_cta="Revisar estratégia de aditivo",
        cta_connected=True,
        maintenance_owner="none",
        refresh_policy="n/a",
        proposed_url="/respostas/aditivo-25-ilegal/",
        existing_url=None,
        independent_utility=False,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=True,
        claims_national=False,
        components={
            "commercial_pain_ticket": 0.5,
            "data_coverage_freshness": 0.4,
            "proprietary_differentiation": 0.2,
            "citability": 0.2,
            "time_to_publish": 0.5,
            "maintenance_cost": 0.4,
        },
    ),
    _candidate(
        opportunity_id="tof-sinapi-desonerado-duplicate",
        family="C",
        question="Qual base usar e como alinhar BDI e encargos?",
        visitor_job="Escolher SINAPI desonerado vs não desonerado.",
        search_intent="commercial",
        audience="orcamentista",
        funnel_stage="mofu",
        commercial_pain="Erro de base destrói margem.",
        offer_bridge={
            "service_slug": "auditoria-orcamento-licitacao",
            "service_path": "/auditoria-orcamento-licitacao/",
            "why": "Página editorial já existe.",
        },
        geographic_scope={"kind": "method", "codes": [], "label": "método"},
        temporal_scope={"start": None, "end": None, "as_of": CATALOG_AS_OF},
        grain="edital × base SINAPI",
        coverage={**METHOD_COVERAGE, "sources": ["scripts/organic/demand_graph.py#need-sinapi-desonerado"]},
        market_job={"present": True, "plausibility": 0.85, "text": "desonerado e não desonerado"},
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="Ativo editorial já publicado.",
        unknown=[],
        factual_answer_outline="Pergunta idêntica a /conteudos/sinapi-desonerado-nao-desonerado/.",
        unique_insight="",
        unique_insight_key="",
        calculations={},
        limitations=["Duplicata de ativo existente."],
        prohibited_claims=["Nova URL para a mesma pergunta."],
        suggested_visuals=[],
        suggested_internal_links=["/conteudos/sinapi-desonerado-nao-desonerado/"],
        suggested_cta="Auditar orçamento e BDI do edital",
        cta_connected=True,
        maintenance_owner="web-cfg-editorial",
        refresh_policy="MERGE",
        proposed_url="/conteudos/sinapi-desonerado-nao-desonerado/",
        existing_url="/conteudos/sinapi-desonerado-nao-desonerado/",
        duplicate_of="/conteudos/sinapi-desonerado-nao-desonerado/",
        merge_into="/conteudos/sinapi-desonerado-nao-desonerado/",
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        components={
            "commercial_pain_ticket": 0.85,
            "data_coverage_freshness": 0.6,
            "proprietary_differentiation": 0.5,
            "citability": 0.5,
            "time_to_publish": 0.95,
            "maintenance_cost": 0.2,
        },
    ),
    _candidate(
        opportunity_id="tof-stale-ticket-sc",
        family="A",
        question="Qual era o ticket de edificação pública em SC no recorte encerrado e não atualizado?",
        visitor_job="Usar um número velho como se fosse vigente.",
        search_intent="informational",
        audience="diretor-construtora",
        funnel_stage="tofu",
        commercial_pain="Âncora desatualizada.",
        offer_bridge={
            "service_slug": "metodologia-inteligencia",
            "service_path": "/metodologia-inteligencia/",
            "why": "Freshness gate.",
        },
        geographic_scope=SCOPE_SC,
        temporal_scope={"start": "2018-01-01", "end": "2019-12-31", "as_of": "2020-01-01"},
        grain="archetype × UF × período",
        coverage={
            "state": "stale",
            "kind": "aggregate",
            "record_count": 40,
            "stale": True,
            "complete_for_scope": True,
            "nacional_completo": False,
            "as_of": "2020-01-01",
            "sources": ["historical-fixture"],
        },
        market_job={"present": True, "plausibility": 0.5, "text": "ticket antigo SC"},
        search_signal={"gsc_present": False, "impressions": 0, "clicks": 0, "position": 0, "related_queries": []},
        distinctive_edge="",
        unknown=["Snapshot vigente."],
        factual_answer_outline="as_of 2020-01-01 está stale frente à política de 48h/publicação vigente.",
        unique_insight="",
        unique_insight_key="stale-ticket",
        calculations={"n": 40},
        limitations=["Freshness stale."],
        prohibited_claims=["Número de 2019 como mercado atual."],
        suggested_visuals=[],
        suggested_internal_links=["/respostas/ticket-tipico-edificacao-publica-sc/"],
        suggested_cta="Ver metodologia e limites da inteligência de mercado",
        cta_connected=True,
        maintenance_owner="public-read freshness",
        refresh_policy="HOLD",
        proposed_url="/respostas/ticket-edificacao-sc-2019/",
        existing_url=None,
        independent_utility=True,
        method_reproducible=True,
        is_doorway=False,
        generic_no_edge=False,
        unsupported_legal_claim=False,
        claims_national=False,
        freshness_stale=True,
        components={
            "commercial_pain_ticket": 0.7,
            "data_coverage_freshness": 0.9,
            "proprietary_differentiation": 0.7,
            "citability": 0.6,
            "time_to_publish": 0.8,
            "maintenance_cost": 0.3,
        },
    ),
)
