"""Audited EMAIL_VALIDATED gold cases, version 1.

Every case is a real account/person/email observation from Track A, PR #392
canary evidence, or committed public campaign artifacts. Labels are benchmark
verdicts, not send authorization.

VALIDATED_DIRECT and INFERRED_HIGH are absent on purpose: Track A reported 0
honest EMAIL_VALIDATED after rejecting false positives, and no domain in this
pool has two observed person emails that would corroborate a high pattern.
"""

from __future__ import annotations

import json
from pathlib import Path

from scripts.decision_unit_intelligence.email_validated.policy import POLICY_VERSION
from scripts.decision_unit_intelligence.email_validated.schema import (
    GOLD_SET_VERSION,
    AdjudicationRecord,
)

SKEW = {
    "VALIDATED_DIRECT": {
        "count": 0,
        "reason": (
            "PR #392 Track A canary: 0 honest EMAIL_VALIDATED after rejecting "
            "lawyer/ethics/brand/capital false positives. No invented positives."
        ),
    },
    "INFERRED_HIGH": {
        "count": 0,
        "reason": (
            "No domain in this pool has two or more OBSERVED person mailboxes "
            "needed to corroborate a high-confidence org pattern. Single-sample "
            "patterns stay INFERRED_UNVERIFIED."
        ),
    },
}


def _case(
    case_id: str,
    *,
    account_id: str,
    company: str,
    email: str | None,
    person_name: str | None,
    role: str | None,
    epistemic: str,
    source: str,
    source_date: str | None,
    source_url: str | None,
    frozen_evidence: str | None,
    identity_association: str,
    affiliation: str,
    technical_status: str,
    freshness: str,
    human_verdict: str,
    notes: str,
    split: str,
    engine: str,
    suppression: str = "NONE",
    score: float | None = None,
    third_party_echo: bool = False,
    approved_exception: str | None = None,
) -> AdjudicationRecord:
    return AdjudicationRecord(
        case_id=case_id,
        account_id=account_id,
        company=company,
        account_legal_name=company,
        email=email,
        person_name=person_name,
        role=role,
        epistemic=epistemic,
        source=source,
        source_date=source_date,
        source_url=source_url,
        frozen_evidence=frozen_evidence,
        identity_association=identity_association,
        affiliation=affiliation,
        technical_status=technical_status,
        freshness=freshness,
        human_verdict=human_verdict,
        notes=notes,
        policy_version=POLICY_VERSION,
        gold_set_version=GOLD_SET_VERSION,
        split=split,
        suppression=suppression,
        engine=engine,
        score=score,
        third_party_echo=third_party_echo,
        approved_exception=approved_exception,
    )


def build_gold_cases() -> list[AdjudicationRecord]:
    return [
        # --- development: policy-writing exemplars (do not leak into holdout) ---
        _case(
            "evg1-001",
            account_id="00820854000114",
            company="QUALIDADE MINERACAO LTDA",
            email="contato@qualidademineracao.com.br",
            person_name="EDUARDO SCHMITT ESPINDOLA",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://qualidademineracao.com.br/",
            frozen_evidence="contato@qualidademineracao.com.br on company site; QSA Eduardo Schmitt Espindola",
            identity_association="NONE",
            affiliation="UNCLEAR",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Track A: generic contato@ next to QSA. Score overlay 0.99 must not promote.",
            split="development",
            engine="score_overlay",
            score=0.99,
        ),
        _case(
            "evg1-002",
            account_id="52639513000140",
            company="INFRAPAV CONSTRUCOES LTDA",
            email="adm@infrapav.com.br",
            person_name="KELLY NUNES",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="third_party_directory",
            source_date="2026-08-05",
            source_url="https://casadosdados.com.br/solucao/cnpj/infrapav-construcoes-ltda-52639513000140",
            frozen_evidence="adm@infrapav.com.br listed on Casa dos Dados; QSA Kelly Nunes",
            identity_association="NONE",
            affiliation="UNCLEAR",
            technical_status="MX_PRESENT",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="MX present on a generic adm@ is not identity. CasadosDados is echo.",
            split="development",
            engine="mx_overlay",
            third_party_echo=True,
        ),
        _case(
            "evg1-003",
            account_id="00820854000114",
            company="QUALIDADE MINERACAO LTDA",
            email="eduardo.espindola@qualidademineracao.com.br",
            person_name="EDUARDO SCHMITT ESPINDOLA",
            role="Sócio-Administrador",
            epistemic="INFERRED",
            source="org_email_pattern",
            source_date="2026-08-05",
            source_url="https://qualidademineracao.com.br/",
            frozen_evidence="Inferred first.last from QSA Eduardo Schmitt Espindola + domain qualidademineracao.com.br",
            identity_association="NONE",
            affiliation="UNCLEAR",
            technical_status="MX_PRESENT",
            freshness="FRESH",
            human_verdict="INFERRED_UNVERIFIED",
            notes="Pattern candidate. INFERRED stays INFERRED even with MX.",
            split="development",
            engine="org-email-pattern.v1",
        ),
        _case(
            "evg1-004",
            account_id="00820854000114",
            company="QUALIDADE MINERACAO LTDA",
            email="contato@qualidademineracao.com.br",
            person_name="EDUARDO SCHMITT ESPINDOLA",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://qualidademineracao.com.br/",
            frozen_evidence="Site lists contato@qualidademineracao.com.br. QSA is Eduardo Schmitt Espindola.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Generic mailbox is not a person even when QSA is known.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-005",
            account_id="82743832000162",
            company="PLANATERRA-TERRAPLENAGEM E PAVIMENTACAO LTDA",
            email="licitacao1@planaterra.com.br",
            person_name="GERSON DE BORBA DIAS",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="official_document",
            source_date="2023-07-01",
            source_url="https://ilhota.sc.gov.br/wp-content/uploads/2023/07/2242997_Habilitacao_da_Empresa___PLANATERRA_TERRAPLANAGEM_E_PAVIMENTACAO_LTDA.pdf",
            frozen_evidence="licitacao1@planaterra.com.br on 2023 municipal habilitation PDF; QSA Gerson de Borba Dias",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="STALE",
            human_verdict="GENERIC_ROLE",
            notes="Role mailbox licitacao1@ from a 2023 PDF. Not a person.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-006",
            account_id="83665141000150",
            company="SETEP CONSTRUCOES S.A",
            email="setep@setep.com.br",
            person_name="JOSE ROBERTO DE SOUZA",
            role="Diretor",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://www.setep.com.br/",
            frozen_evidence="Brand mailbox setep@setep.com.br on institutional page near director José Roberto",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_PERSON",
            notes="PR #392 FP: brand mailbox is not José Roberto. Promoting this is stop-the-line.",
            split="development",
            engine="pr392_canary",
        ),
        _case(
            "evg1-007",
            account_id="27743102000153",
            company="FJ CONSTRUTORA",
            email="jeferson@fjconstrutora.com.br",
            person_name="JEFERSON RADTKE",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="official_document",
            source_date="2022-10-01",
            source_url="https://novatrento.sc.gov.br/uploads/sites/349/2022/10/Processo-121_2022-CC-002_2022-Parte-3.pdf",
            frozen_evidence="jeferson@fjconstrutora.com.br in 2022 Nova Trento process PDF; QSA Jeferson Radtke",
            identity_association="UNRESOLVED",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="STALE",
            human_verdict="OBSERVED_BUT_STALE",
            notes="Named local-part + matching QSA, but 2022 PDF and first-name-only. Not EMAIL_VALIDATED.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-008",
            account_id="03620927000112",
            company="PAVIPLAN PAVIMENTACAO LTDA",
            email="comercial@paviplan.com.br",
            person_name="MAURICIO VOGELSANGER",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://paviplan.com.br/politica-de-privacidade/",
            frozen_evidence="comercial@paviplan.com.br on privacy page; QSA Mauricio Vogelsanger",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Suppression overlay: DNC on a role mailbox still must not promote.",
            split="development",
            engine="suppression_overlay",
            suppression="DNC",
        ),
        _case(
            "evg1-009",
            account_id="29095199000160",
            company="PAVIMENTAR ENGENHARIA E CONSTRUÇÕES LTDA",
            email=None,
            person_name="ANDRE MARTINS LEONARDO",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A CRM: no email, no site. QSA Andre Martins Leonardo / Edmar Ciro de Oliveira.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Missing provenance URL and missing email. Policy example for missing provenance.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-010",
            account_id="05133291000100",
            company="STRABE COMERCIO E CONSTRUCOES LTDA",
            email="societario.sbs@fiscallcontabilidade.com.br",
            person_name="LILIAN BAUMEL MAAHS",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="third_party_directory",
            source_date="2026-08-05",
            source_url="https://casadosdados.com.br/solucao/cnpj/strabe-comercio-e-construcoes-ltda-05133291000100",
            frozen_evidence="societario.sbs@fiscallcontabilidade.com.br — accounting-firm domain, not Strabe",
            identity_association="NONE",
            affiliation="THIRD_PARTY",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_COMPANY",
            notes="Holding/accounting mailbox. Company of the email is Fiscal L, not Strabe.",
            split="development",
            engine="track_a_crm",
            third_party_echo=True,
        ),
        _case(
            "evg1-011",
            account_id="03094645000129",
            company="INFRASUL - INFRAESTRUTURA E EMPREENDIMENTOS LTDA",
            email="infraestrutura@infrasul.com.br",
            person_name="LUIZ ANTONIO VALLE PEDREIRA DE CERQUEIRA",
            role="Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://www.infrasul.com.br/contato/",
            frozen_evidence="infraestrutura@infrasul.com.br on /contato. Socio is INFRA ENGENHARIA HOLDING LTDA.",
            identity_association="NONE",
            affiliation="HOLDING",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Role mailbox + holding shareholder. Not a named person channel.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-012",
            account_id="82743832000162",
            company="PLANATERRA-TERRAPLENAGEM E PAVIMENTACAO LTDA",
            email="ricardocoelho@ricardocoelho.adv.br",
            person_name="RICARDO COELHO",
            role="Chief Compliance Officer",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-03-04",
            source_url="https://planaterra.com.br/2026/03/04/programa-de-compliance-planaterra/",
            frozen_evidence="Compliance page publishes ricardocoelho@ricardocoelho.adv.br — third-party law firm",
            identity_association="UNRESOLVED",
            affiliation="THIRD_PARTY",
            technical_status="NONE",
            freshness="AGING",
            human_verdict="WRONG_COMPANY",
            notes="PR #392 FP: lawyer domain is not Planaterra identity.",
            split="development",
            engine="pr392_canary",
            third_party_echo=True,
        ),
        _case(
            "evg1-013",
            account_id="82743832000162",
            company="PLANATERRA-TERRAPLENAGEM E PAVIMENTACAO LTDA",
            email="conduta@planaterra.com.br",
            person_name=None,
            role="Canal de ética",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-03-04",
            source_url="https://planaterra.com.br/2026/03/04/programa-de-compliance-planaterra/",
            frozen_evidence="Ethics mailbox conduta@planaterra.com.br on compliance program page",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="AGING",
            human_verdict="GENERIC_ROLE",
            notes="PR #392: conduta@ never becomes a person.",
            split="development",
            engine="pr392_canary",
        ),
        _case(
            "evg1-014",
            account_id="83665141000150",
            company="SETEP CONSTRUCOES S.A",
            email="vitoria@setep.com.br",
            person_name=None,
            role="Escritório Vitória",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://www.setep.com.br/",
            frozen_evidence="Capital/office mailbox vitoria@setep.com.br rejected as non-person in PR #392",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Office/city mailbox is generic, not a person named Vitória.",
            split="development",
            engine="pr392_canary",
        ),
        _case(
            "evg1-015",
            account_id="21157133000146",
            company="BRITAX BRITAGEM E CONSTRUÇÕES LTDA",
            email="comercial@britax.ind.br",
            person_name="VALMIR PATZLAFF",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="third_party_directory",
            source_date="2026-08-05",
            source_url="https://casadosdados.com.br/solucao/cnpj/britax-britagem-e-construcoes-ltda-21157133000146",
            frozen_evidence="comercial@britax.ind.br echoed on Casa dos Dados; QSA Valmir Patzlaff",
            identity_association="NONE",
            affiliation="UNCLEAR",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Third-party directory echo is not identity association.",
            split="development",
            engine="track_a_crm",
            third_party_echo=True,
        ),
        _case(
            "evg1-016",
            account_id="01341214000194",
            company="CONCISA PAVIMENTAÇÃO E TERRAPLANAGEM LTDA",
            email="rh@concisa.eng.br",
            person_name="DANILO CONTE",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="professional_profile",
            source_date="2026-08-05",
            source_url="https://www.linkedin.com/company/concisapavterraplanagem",
            frozen_evidence="rh@concisa.eng.br; QSA Danilo Conte and Ellen Conte (two names, one mailbox)",
            identity_association="AMBIGUOUS",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="OBSERVED_BUT_IDENTITY_AMBIGUOUS",
            notes="Two sócios-administradores share one RH mailbox. Ambiguous person link.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-017",
            account_id="52639513000140",
            company="INFRAPAV CONSTRUCOES LTDA",
            email="kelly.nunes@infrapav.com.br",
            person_name="KELLY NUNES",
            role="Sócio-Administrador",
            epistemic="INFERRED",
            source="org_email_pattern",
            source_date="2026-08-05",
            source_url="https://infrapav.com.br/",
            frozen_evidence="Inferred kelly.nunes@infrapav.com.br from QSA + domain. Observed mailbox is adm@.",
            identity_association="NONE",
            affiliation="UNCLEAR",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="INFERRED_UNVERIFIED",
            notes="INFERRED must not be rewritten to OBSERVED.",
            split="development",
            engine="org-email-pattern.v1",
        ),
        _case(
            "evg1-018",
            account_id="84689066000392",
            company="BRITAGEM VOGELSANGER LTDA",
            email="mauricio.vogelsanger@britagemvogelsanger.com.br",
            person_name="MAURICIO VOGELSANGER",
            role="Sócio-Administrador",
            epistemic="INFERRED",
            source="org_email_pattern",
            source_date="2026-08-05",
            source_url="https://britagemvogelsanger.com.br/sobre-nos/",
            frozen_evidence="Mauricio Vogelsanger is QSA of PAVIPLAN (03620927000112), not Britagem Vogelsanger",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_COMPANY",
            notes="Homonym/surname collision: Mauricio is Paviplan, Marcos/Mario are Britagem.",
            split="development",
            engine="homonym_probe",
        ),
        _case(
            "evg1-019",
            account_id="04406660000128",
            company="TERRAMAX - CONSTRUCOES E OBRAS LTDA",
            email="terramax@terramaxobras.com.br",
            person_name="EDUARDO LARI ROSSETTO",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="official_document",
            source_date="2023-07-01",
            source_url="https://xanxere.sc.gov.br/uploads/sites/92/2023/07/285496_0.127160001302279284_questionamento_tp_0008.pdf",
            frozen_evidence="terramax@terramaxobras.com.br brand mailbox on 2023 Xanxerê PDF",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="STALE",
            human_verdict="GENERIC_ROLE",
            notes="Brand mailbox on stale official PDF.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-020",
            account_id="03257777000124",
            company="GAIA RODOVIAS LTDA.",
            email="gaiarodovias@gaiarodovias.com.br",
            person_name="CRISTIAN TICIANI",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://gaiarodovias.com.br/",
            frozen_evidence="Brand mailbox gaiarodovias@gaiarodovias.com.br on company homepage",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Brand@domain is not Cristian Ticiani.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-021",
            account_id="95865044000190",
            company="ZANCO CONSTRUTORA LTDA",
            email=None,
            person_name="FABIANE ZANCO BORTOLANZA",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: empty email, no site. QSA Fabiane Zanco Bortolanza.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Named decision-maker with no mailbox. Coverage must not invent one.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-022",
            account_id="23773012000154",
            company="CONSORCIO INTERMUNICIPAL DE DESENVOLVIMENTO REGIONAL - CONDER",
            email=None,
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: consortium account, no QSA, no email, no site.",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="No person, no email. UNKNOWN remains visible.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-023",
            account_id="12535370000102",
            company="TERRABASE TERRAPLENAGEM  LTDA",
            email="engenharia1@terrabaseterraplenagem.com.br",
            person_name="JARDEL FLORIANI",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://terrabaseterraplenagem.com.br/",
            frozen_evidence="engenharia1@terrabaseterraplenagem.com.br on company site; QSA Jardel Floriani",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Department mailbox engenharia1@ is not Jardel.",
            split="development",
            engine="track_a_crm",
        ),
        _case(
            "evg1-024",
            account_id="07455659000181",
            company="LZK CONSTRUTORA LTDA",
            email="adm@lzkconstrutora.com.br",
            person_name="FERNANDO LAZAREK",
            role="Administrador",
            epistemic="OBSERVED",
            source="third_party_directory",
            source_date="2026-08-05",
            source_url="https://casadosdados.com.br/solucao/cnpj/lzk-construtora-ltda-07455659000262",
            frozen_evidence="adm@lzkconstrutora.com.br on Casa dos Dados (branch CNPJ echo); QSA Fernando Lazarek",
            identity_association="NONE",
            affiliation="UNCLEAR",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="adm@ + directory echo. Not Fernando.",
            split="development",
            engine="track_a_crm",
            third_party_echo=True,
        ),
        _case(
            "evg1-025",
            account_id="27743102000153",
            company="FJ CONSTRUTORA",
            email="jeferson.radtke@fjconstrutora.com.br",
            person_name="JEFERSON RADTKE",
            role="Sócio-Administrador",
            epistemic="INFERRED",
            source="org_email_pattern",
            source_date="2026-08-05",
            source_url="https://novatrento.sc.gov.br/uploads/sites/349/2022/10/Processo-121_2022-CC-002_2022-Parte-3.pdf",
            frozen_evidence="Inferred first.last while observed mailbox is jeferson@. Must stay INFERRED.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="STALE",
            human_verdict="INFERRED_UNVERIFIED",
            notes="Nearby observed first-name mailbox does not upgrade an inferred first.last.",
            split="development",
            engine="org-email-pattern.v1",
        ),
        _case(
            "evg1-026",
            account_id="00758756000102",
            company="CONSTRUTORA ANCAR LTDA",
            email="junior@alamedacom.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="contact_enrichment",
            source_date="2026-08-10",
            source_url="https://ancar.com.br/",
            frozen_evidence="reuse_graph maps junior@alamedacom.com.br → CNPJ 00758756000102 (Ancar), domain is Alameda",
            identity_association="UNRESOLVED",
            affiliation="THIRD_PARTY",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_COMPANY",
            notes="Email domain belongs to Alameda, account is Ancar. Cross-company leak.",
            split="development",
            engine="contact_enrichment_reuse_graph",
        ),
        _case(
            "evg1-027",
            account_id="05895635000118",
            company="JR CONSTRUCOES E TERRAPLENAGEM LTDA EPP",
            email="arantes@terraplenagem.com",
            person_name="EDERSON RODRIGUES",
            role="Administrador",
            epistemic="OBSERVED",
            source="contact_enrichment",
            source_date="2026-08-10",
            source_url=None,
            frozen_evidence="reuse_graph maps arantes@terraplenagem.com → JR CNPJ 05895635000118. Domain is not JR.",
            identity_association="NONE",
            affiliation="THIRD_PARTY",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_PERSON",
            notes="Mailbox local-part Arantes is not Ederson Rodrigues; domain is not JR.",
            split="development",
            engine="contact_enrichment_reuse_graph",
        ),
        _case(
            "evg1-028",
            account_id="03620927000112",
            company="PAVIPLAN PAVIMENTACAO LTDA",
            email="marcos.vogelsanger@paviplan.com.br",
            person_name="MARCOS VOGELSANGER",
            role="Administrador",
            epistemic="INFERRED",
            source="org_email_pattern",
            source_date="2026-08-05",
            source_url="https://paviplan.com.br/",
            frozen_evidence="Marcos Vogelsanger is administrador of Britagem Vogelsanger, not Paviplan (Mauricio/Marta)",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_COMPANY",
            notes="Inverse homonym of evg1-018. Surname is not company membership.",
            split="development",
            engine="homonym_probe",
        ),
        # --- holdout: observational labels, disjoint case_ids, unused as rule examples ---
        _case(
            "evg1-029",
            account_id="03620927000112",
            company="PAVIPLAN PAVIMENTACAO LTDA",
            email="comercial@paviplan.com.br",
            person_name="MARTA REGINA VOGELSANGER",
            role="Sócio",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://paviplan.com.br/politica-de-privacidade/",
            frozen_evidence="Same comercial@ mailbox; second QSA Marta Regina Vogelsanger",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Holdout: second person on the same role mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-030",
            account_id="10249046000100",
            company="CONSTRUCOES SCHOROEDER EIRELI    -",
            email="contato@schoroeder.com.br",
            person_name="ALEXANDRE MENDES SCHOROEDER",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://schoroeder.com.br/",
            frozen_evidence="contato@schoroeder.com.br on company homepage; QSA Alexandre Mendes Schoroeder",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Holdout generic contato@.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-031",
            account_id="12218083000179",
            company="BCL EMPREENDIMENTO LTDA",
            email=None,
            person_name="JOAO ALBERTO LIBRELATO",
            role="Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. Socio NEWCO LIBRELATO PARTICIPACOES LTDA (holding).",
            identity_association="NONE",
            affiliation="HOLDING",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Holdout: holding-backed account without a mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-032",
            account_id="09223659000181",
            company="VIGA - PAVIMENTACAO E OBRAS LTDA.",
            email=None,
            person_name="LUCCA MATHEUS D AGOSTINI",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. QSA Lucca Matheus D Agostini / Marcos Fernandes Gaspar de Lima.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Holdout unknown mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-033",
            account_id="22798043000105",
            company="KAENG INFRAESTRUTURA LTDA",
            email=None,
            person_name="JEAN CLAUDE CESCA",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. Socio INCA 3 ADMINISTRADORA DE BENS LTDA.",
            identity_association="NONE",
            affiliation="HOLDING",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Holdout holding + no mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-034",
            account_id="01650178000140",
            company="CR ARTEFATOS DE CIMENTO LTDA",
            email=None,
            person_name="WALNEY AGILIO RAIMONDI",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. QSA Walney Agilio Raimondi.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Holdout unknown.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-035",
            account_id="80996861000100",
            company="PROSUL PROJETOS SUPERVISAO E PLANEJAMENTO LTDA",
            email=None,
            person_name="WILFREDO BRILLINGER",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://www.prosul.com/termos-de-uso/",
            frozen_evidence="Track A empty email; site terms page only. QSA Wilfredo Brillinger / Maria das Gracas Carvalho Brillinger.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="FRESH",
            human_verdict="UNKNOWN",
            notes="Site exists, mailbox does not.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-036",
            account_id="80095466000157",
            company="CONSTRUTORA OLIVEIRA LTDA",
            email=None,
            person_name="ALAMIR CARLOS DE OLIVEIRA",
            role="Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A empty email. Administrators Alamir, Alcyone, Lenoir de Oliveira + three holdings.",
            identity_association="NONE",
            affiliation="HOLDING",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Homonym-rich Oliveira family, no mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-037",
            account_id="80095466000157",
            company="CONSTRUTORA OLIVEIRA LTDA",
            email=None,
            person_name="ALCYONE CESAR DE OLIVEIRA",
            role="Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Second Oliveira administrator, still no published mailbox.",
            identity_association="NONE",
            affiliation="HOLDING",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Second person, same account, still UNKNOWN.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-038",
            account_id="74111709000109",
            company="ENGETOM CONSTRUCAO CIVIL LTDA",
            email=None,
            person_name="BRENDA DAL PONT TOMASI",
            role="Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://www.engetom.com.br/Index.html",
            frozen_evidence="Track A: site exists, no email captured. QSA Brenda Dal Pont Tomasi / Luiz Tomasi.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="FRESH",
            human_verdict="UNKNOWN",
            notes="Public site without a captured mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-039",
            account_id="43887548000108",
            company="CONSTRUTORA SCHROEDER E SCHMIDT LTDA",
            email=None,
            person_name="ANDERSON MINATTI SCHMIDT",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. QSA Anderson Minatti Schmidt / Guilherme Jorge Schroeder.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Distinct from Schoroeder (evg1-030). Homonym-ish corporate names.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-040",
            account_id="03574370000120",
            company="EMPREITEIRA DE MÃO DE OBRA ADRIMAR EIRELI",
            email=None,
            person_name="MARCELO BENVENUTTI",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. QSA Marcelo Benvenutti.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Holdout unknown.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-041",
            account_id="06145928000140",
            company="CONSTRUÇÃO CIVIL MG LTDA",
            email=None,
            person_name="LUSMARINA PARISI GRABOWSKI",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A: no email/site. QSA Lusmarina Parisi Grabowski.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Holdout unknown.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-042",
            account_id="84689066000392",
            company="BRITAGEM VOGELSANGER LTDA",
            email=None,
            person_name="MARCOS VOGELSANGER",
            role="Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://britagemvogelsanger.com.br/sobre-nos/",
            frozen_evidence="Sobre-nós page, no mailbox. Administrators Marcos and Mario Vogelsanger.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="FRESH",
            human_verdict="UNKNOWN",
            notes="Real Vogelsanger at Britagem. Contrast with inferred Mauricio case.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-043",
            account_id="84689066000392",
            company="BRITAGEM VOGELSANGER LTDA",
            email=None,
            person_name="MARIO VOGELSANGER",
            role="Administrador",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-05",
            source_url="https://britagemvogelsanger.com.br/sobre-nos/",
            frozen_evidence="Second administrator Mario Vogelsanger, still no mailbox on sobre-nós.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="FRESH",
            human_verdict="UNKNOWN",
            notes="Sibling/homonym pair on the correct company, still UNKNOWN.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-044",
            account_id="07351538000190",
            company="GARDEN CONSULTORIA PROJETOS E GESTAO LTDA",
            email="contato@garden.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://garden.com.br/contato",
            frozen_evidence="contato@garden.com.br on official contact page (expand-esr-20260810 human-review)",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Campaign artifact labeled enrollable/VERIFIED still generic. Not EMAIL_VALIDATED.",
            split="holdout",
            engine="contact_enrichment",
        ),
        _case(
            "evg1-045",
            account_id="07792269000105",
            company="CONSTRUTORA LYTORANEA LTDA - EM RECUPERACAO JUDICIAL",
            email="lytoranea@lytoranea.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://lytoranea.com.br/contato",
            frozen_evidence="Brand mailbox lytoranea@lytoranea.com.br on /contato",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Brand mailbox in campaign human-review pack.",
            split="holdout",
            engine="contact_enrichment",
        ),
        _case(
            "evg1-046",
            account_id="08150094000197",
            company="MATERA ENGENHARIA LTDA",
            email="imprensa@matera.com",
            person_name=None,
            role="Imprensa",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://matera.com.br/fale-conosco",
            frozen_evidence="imprensa@matera.com on fale-conosco (role/press mailbox)",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Press mailbox is a role, not a decision-maker.",
            split="holdout",
            engine="contact_enrichment",
        ),
        _case(
            "evg1-047",
            account_id="00061493000170",
            company="ENCOPAV ENGENHARIA LTDA",
            email="encopav@encopav.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://encopav.com.br/contato",
            frozen_evidence="Brand mailbox encopav@encopav.com.br; mailbox_purpose UNKNOWN in clean-cohort-send-ready",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Prior email_send_ready=true on a brand box. This policy refuses promotion.",
            split="holdout",
            engine="clean_cohort_send_ready",
        ),
        _case(
            "evg1-048",
            account_id="00220982000127",
            company="MATT CONSTRUTORA LTDA",
            email="contato@mattconstrutora.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://www.mattconstrutora.com.br/",
            frozen_evidence="contato@mattconstrutora.com.br; mailbox_purpose GENERIC_CONTACT",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Holdout generic from clean cohort.",
            split="holdout",
            engine="clean_cohort_send_ready",
        ),
        _case(
            "evg1-049",
            account_id="57623761000117",
            company="DNP - TERRAPLENAGEM E PAVIMENTADORA FORESTO LTDA.",
            email="aweinstein@dnp.com",
            person_name=None,
            role="aweinstein",
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://dnp.com",
            frozen_evidence="aweinstein@dnp.com scraped from https://dnp.com; feed role field is the local-part only",
            identity_association="UNRESOLVED",
            affiliation="UNCLEAR",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="OBSERVED_BUT_IDENTITY_AMBIGUOUS",
            notes="Closest-to-positive in the pool: nominal local-part, no named person, no snippet.",
            split="holdout",
            engine="clean_cohort_send_ready",
        ),
        _case(
            "evg1-050",
            account_id="03222465000185",
            company="DALBA ENGENHARIA E EMPREENDIMENTOS LTDA - EM RECUPERACAO JUDICIAL",
            email="dalbapiedmont@dalba.com",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="company_website",
            source_date="2026-08-10",
            source_url="https://dalba.com/",
            frozen_evidence="dalbapiedmont@dalba.com — office/branch local-part, not a person",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="GENERIC_ROLE",
            notes="Branch mailbox Piedmont is not identity.",
            split="holdout",
            engine="clean_cohort_send_ready",
        ),
        _case(
            "evg1-051",
            account_id="01341214000194",
            company="CONCISA PAVIMENTAÇÃO E TERRAPLANAGEM LTDA",
            email=None,
            person_name="EVELIN CONTE",
            role="Sócio",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url="https://www.linkedin.com/company/concisapavterraplanagem",
            frozen_evidence="Track A qsa2: EVELIN CONTE (Sócio). Only published mailbox is rh@.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="FRESH",
            human_verdict="UNKNOWN",
            notes="Third Conte family member, no personal mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-052",
            account_id="04406660000128",
            company="TERRAMAX - CONSTRUCOES E OBRAS LTDA",
            email="terramax@terramaxobras.com.br",
            person_name="THIAGO ADOLFO ALVARES ROSSETTO",
            role="Sócio",
            epistemic="OBSERVED",
            source="official_document",
            source_date="2023-07-01",
            source_url="https://xanxere.sc.gov.br/uploads/sites/92/2023/07/285496_0.127160001302279284_questionamento_tp_0008.pdf",
            frozen_evidence="Same brand mailbox as evg1-019 attributed to second QSA Thiago Rossetto",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="STALE",
            human_verdict="GENERIC_ROLE",
            notes="Holdout second person on brand mailbox.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-053",
            account_id="82743832000162",
            company="PLANATERRA-TERRAPLENAGEM E PAVIMENTACAO LTDA",
            email="licitacao1@planaterra.com.br",
            person_name="GUILHERME DE AZEVEDO DIAS",
            role="Sócio-Administrador",
            epistemic="OBSERVED",
            source="official_document",
            source_date="2023-07-01",
            source_url="https://ilhota.sc.gov.br/wp-content/uploads/2023/07/2242997_Habilitacao_da_Empresa___PLANATERRA_TERRAPLANAGEM_E_PAVIMENTACAO_LTDA.pdf",
            frozen_evidence="Same licitacao1@ as evg1-005, second sócio-administrador Guilherme de Azevedo Dias",
            identity_association="AMBIGUOUS",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="STALE",
            human_verdict="OBSERVED_BUT_IDENTITY_AMBIGUOUS",
            notes="Two sócios, one role mailbox, stale PDF.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-054",
            account_id="03257777000124",
            company="GAIA RODOVIAS LTDA.",
            email="cristian.ticiani@gaiarodovias.com.br",
            person_name="CRISTIAN TICIANI",
            role="Sócio-Administrador",
            epistemic="INFERRED",
            source="org_email_pattern",
            source_date="2026-08-05",
            source_url="https://gaiarodovias.com.br/",
            frozen_evidence="Inferred first.last; observed mailbox is brand gaiarodovias@",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="INFERRED_UNVERIFIED",
            notes="Holdout inferred candidate. Must remain INFERRED.",
            split="holdout",
            engine="org-email-pattern.v1",
        ),
        _case(
            "evg1-055",
            account_id="95865044000190",
            company="ZANCO CONSTRUTORA LTDA",
            email=None,
            person_name="MARILENE MARIA ZAPANI ZANCO",
            role="Sócio",
            epistemic="OBSERVED",
            source="historical_campaign",
            source_date="2026-08-05",
            source_url=None,
            frozen_evidence="Track A qsa2 Marilene Maria Zapani Zanco; still no mailbox.",
            identity_association="NONE",
            affiliation="DEFENSIBLE",
            technical_status="UNKNOWN",
            freshness="UNKNOWN",
            human_verdict="UNKNOWN",
            notes="Second Zanco person, still UNKNOWN.",
            split="holdout",
            engine="track_a_crm",
        ),
        _case(
            "evg1-056",
            account_id="08150094000197",
            company="MATERA ENGENHARIA LTDA",
            email="voce@empresa.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="contact_enrichment",
            source_date="2026-08-10",
            source_url="https://matera.com.br/fale-conosco",
            frozen_evidence="reuse_graph lists voce@empresa.com.br under Matera CNPJ — placeholder mailbox",
            identity_association="NONE",
            affiliation="NONE",
            technical_status="HARD_FAIL",
            freshness="FRESH",
            human_verdict="UNKNOWN",
            notes="Placeholder email@template. Technical hard-fail, not a person.",
            split="holdout",
            engine="contact_enrichment_reuse_graph",
        ),
        _case(
            "evg1-057",
            account_id="00758756000102",
            company="CONSTRUTORA ANCAR LTDA",
            email="ancar@nectarc.com.br",
            person_name=None,
            role=None,
            epistemic="OBSERVED",
            source="contact_enrichment",
            source_date="2026-08-10",
            source_url="https://ancar.com.br/",
            frozen_evidence="reuse_graph: ancar@nectarc.com.br → Ancar CNPJ. Domain nectarc.com.br is third-party.",
            identity_association="NONE",
            affiliation="THIRD_PARTY",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="WRONG_COMPANY",
            notes="Holdout third-party domain attached to Ancar.",
            split="holdout",
            engine="contact_enrichment_reuse_graph",
        ),
        _case(
            "evg1-058",
            account_id="21157133000146",
            company="BRITAX BRITAGEM E CONSTRUÇÕES LTDA",
            email="comercial@britax.ind.br",
            person_name="BRUNA LAIS KOTHE",
            role="Administrador",
            epistemic="OBSERVED",
            source="third_party_directory",
            source_date="2026-08-05",
            source_url="https://casadosdados.com.br/solucao/cnpj/britax-britagem-e-construcoes-ltda-21157133000146",
            frozen_evidence="Same comercial@ as evg1-015 attributed to second administrator Bruna Lais Kothe",
            identity_association="AMBIGUOUS",
            affiliation="UNCLEAR",
            technical_status="NONE",
            freshness="FRESH",
            human_verdict="OBSERVED_BUT_IDENTITY_AMBIGUOUS",
            notes="Two administrators, one comercial@, directory echo.",
            split="holdout",
            engine="track_a_crm",
            third_party_echo=True,
        ),
    ]


def freeze_gold_set(gold_dir: str | Path) -> dict:
    from scripts.decision_unit_intelligence.email_validated.schema import write_jsonl

    target = Path(gold_dir)
    target.mkdir(parents=True, exist_ok=True)
    cases = build_gold_cases()
    write_jsonl(target / "gold-set.v1.jsonl", cases)
    meta = gold_meta()
    (target / "gold-set.v1.meta.json").write_text(
        json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    development = sorted(case.case_id for case in cases if case.split == "development")
    holdout = sorted(case.case_id for case in cases if case.split == "holdout")
    splits = {
        "gold_set_version": GOLD_SET_VERSION,
        "development": development,
        "holdout": holdout,
        "disjoint": set(development).isdisjoint(holdout),
    }
    (target / "splits.json").write_text(json.dumps(splits, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return meta


def gold_meta() -> dict:
    cases = build_gold_cases()
    by_verdict: dict[str, int] = {}
    by_split: dict[str, int] = {}
    for case in cases:
        by_verdict[case.human_verdict] = by_verdict.get(case.human_verdict, 0) + 1
        by_split[case.split] = by_split.get(case.split, 0) + 1
    return {
        "schema_id": "confenge.email-validated-gold-meta.v1",
        "gold_set_version": GOLD_SET_VERSION,
        "policy_version": POLICY_VERSION,
        "n": len(cases),
        "by_human_verdict": by_verdict,
        "by_split": by_split,
        "skew": SKEW,
        "auto_send": False,
        "gold_label_is_not_send_authorization": True,
        "human_review_approved": False,
        "leakage": {
            "development_used_to_write_policy": True,
            "holdout_frozen_disjoint_case_ids": True,
        },
        "origins": [
            "scripts/decision_unit_intelligence/data/track_a_30.observations.json",
            "PR extra-cli #392 canary (setep@, conduta@, vitoria@, ricardocoelho.adv.br)",
            "artifacts/confenge/contact-enrichment/expand-esr-20260810/",
            "artifacts/confenge/unconditional-go/clean-cohort-send-ready.json",
        ],
    }
