"""CONFENGE public-agency commercial vertical (organs/entities as prospects).

Semantically separate from supplier commercial_leads. Shares the canonical
entrypoint make confenge-commercial-cycle via TARGET=public-agencies|all.
"""

from __future__ import annotations

CAMPAIGN_ID = "CONFENGE-PUBLIC-AGENCY-TECHNICAL-SERVICES-01"
MODULE_VERSION = "1.0.0"
ENTITY_TYPE = "PUBLIC_AGENCY_PROSPECT"

ELIGIBILITY_POTENTIAL = "POTENTIALLY_ELIGIBLE_FOR_DIRECT_CONTRACTING"
SUM_UNKNOWN = "DIRECT_CONTRACTING_SUM_UNKNOWN"

OBJECT_ENGINEERING = "ENGINEERING_SERVICE"
OBJECT_OTHER = "OTHER_SERVICE"
OBJECT_HUMAN = "REQUIRES_HUMAN_LEGAL_CLASSIFICATION"

MODE_REACTIVE = "REACTIVE_OPPORTUNITY"
MODE_PROACTIVE = "PROACTIVE_INSTITUTIONAL_PROSPECT"

FORBIDDEN_ELIGIBILITY_STATES = (
    "DISPENSA_GARANTIDA",
    "CONTRATACAO_DIRETA_AUTORIZADA",
    "ORGAO_PODE_CONTRATAR",
    "SEM_LICITACAO",
    "CONTRATACAO_ASSEGURADA",
)

FISCAL_SUPPORT_PREFERRED = (
    "apoio técnico especializado à fiscalização e à gestão contratual"
)

__all__ = [
    "CAMPAIGN_ID",
    "MODULE_VERSION",
    "ENTITY_TYPE",
    "ELIGIBILITY_POTENTIAL",
    "SUM_UNKNOWN",
    "OBJECT_ENGINEERING",
    "OBJECT_OTHER",
    "OBJECT_HUMAN",
    "MODE_REACTIVE",
    "MODE_PROACTIVE",
]
