"""Professional XLSX generation with formula-injection defense."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo


def neutralize_formula_injection(value: Any) -> Any:
    """Neutralize CSV/Excel formula injection for external/untrusted cell values.

    Cells starting with = + - @ are prefixed with a single quote so spreadsheet
    apps treat them as text. Controlled formulas generated by us must not pass here.
    """
    if value is None:
        return ""
    if isinstance(value, (int, float, bool)):
        return value
    text = str(value)
    if not text:
        return text
    if text[0] in {"=", "+", "-", "@", "\t", "\r"}:
        return "'" + text
    return text


def write_workbook(
    path: Path,
    *,
    title: str,
    summary_rows: list[tuple[str, Any]],
    data_headers: list[str],
    data_rows: list[list[Any]],
    methodology: list[str],
    sources: list[str],
    limitations: list[str],
    sheet_data_name: str = "Dados",
    extra_sheets: dict[str, tuple[list[str], list[list[Any]]]] | None = None,
    provenance: dict[str, Any] | None = None,
) -> Path:
    """Write a structured consulting workbook.

    Sheets: Resumo, main data, optional thematic, Metodologia e fontes.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()

    # Resumo
    ws_sum = wb.active
    if ws_sum is None:  # pragma: no cover — openpyxl always provides active sheet
        raise RuntimeError("Workbook sem planilha ativa")
    ws_sum.title = "Resumo"
    header_fill = PatternFill("solid", fgColor="0B1F33")
    header_font = Font(color="FFFFFF", bold=True)
    ws_sum["A1"] = title
    ws_sum["A1"].font = Font(bold=True, size=14, color="0B1F33")
    ws_sum.merge_cells("A1:B1")
    ws_sum["A2"] = "Documento gerado pelo EXTRA Command Center"
    row_i = 4
    ws_sum.cell(row_i, 1, "Campo").font = header_font
    ws_sum.cell(row_i, 1).fill = header_fill
    ws_sum.cell(row_i, 2, "Valor").font = header_font
    ws_sum.cell(row_i, 2).fill = header_fill
    for key, val in summary_rows:
        row_i += 1
        ws_sum.cell(row_i, 1, neutralize_formula_injection(key))
        ws_sum.cell(row_i, 2, neutralize_formula_injection(val))
    if provenance:
        row_i += 2
        ws_sum.cell(row_i, 1, "Proveniência").font = Font(bold=True)
        for k, v in provenance.items():
            row_i += 1
            ws_sum.cell(row_i, 1, neutralize_formula_injection(k))
            ws_sum.cell(row_i, 2, neutralize_formula_injection(v))
    ws_sum.column_dimensions["A"].width = 32
    ws_sum.column_dimensions["B"].width = 64
    ws_sum.freeze_panes = "A5"

    # Dados
    ws_data = wb.create_sheet(sheet_data_name[:31])
    for col, h in enumerate(data_headers, start=1):
        cell = ws_data.cell(1, col, neutralize_formula_injection(h))
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(wrap_text=True)
    for r_idx, row in enumerate(data_rows, start=2):
        for c_idx, val in enumerate(row, start=1):
            ws_data.cell(r_idx, c_idx, neutralize_formula_injection(val))
    ws_data.auto_filter.ref = f"A1:{get_column_letter(max(1, len(data_headers)))}{max(1, len(data_rows) + 1)}"
    ws_data.freeze_panes = "A2"
    for col in range(1, len(data_headers) + 1):
        ws_data.column_dimensions[get_column_letter(col)].width = min(40, max(12, len(str(data_headers[col - 1])) + 4))
    if data_headers and data_rows:
        try:
            table = Table(
                displayName="TabelaPrincipal",
                ref=f"A1:{get_column_letter(len(data_headers))}{len(data_rows) + 1}",
            )
            table.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
            ws_data.add_table(table)
        except ValueError:
            # Table name uniqueness / edge cases — filters still applied
            pass

    if extra_sheets:
        for name, (headers, rows) in extra_sheets.items():
            ws = wb.create_sheet(str(name)[:31])
            for col, h in enumerate(headers, start=1):
                cell = ws.cell(1, col, neutralize_formula_injection(h))
                cell.font = header_font
                cell.fill = header_fill
            for r_idx, row in enumerate(rows, start=2):
                for c_idx, val in enumerate(row, start=1):
                    ws.cell(r_idx, c_idx, neutralize_formula_injection(val))
            ws.freeze_panes = "A2"
            if headers:
                ws.auto_filter.ref = f"A1:{get_column_letter(len(headers))}{max(1, len(rows) + 1)}"

    # Metodologia e fontes
    ws_m = wb.create_sheet("Metodologia e fontes")
    ws_m["A1"] = "Metodologia"
    ws_m["A1"].font = Font(bold=True, size=12)
    r = 2
    for line in methodology:
        ws_m.cell(r, 1, neutralize_formula_injection(line))
        r += 1
    r += 1
    ws_m.cell(r, 1, "Fontes").font = Font(bold=True, size=12)
    r += 1
    for line in sources:
        ws_m.cell(r, 1, neutralize_formula_injection(line))
        r += 1
    r += 1
    ws_m.cell(r, 1, "Limitações").font = Font(bold=True, size=12)
    r += 1
    for line in limitations:
        ws_m.cell(r, 1, neutralize_formula_injection(line))
        r += 1
    r += 1
    ws_m.cell(r, 1, "Legenda de scores/status: valores derivados são preliminares até revisão humana.")
    ws_m.column_dimensions["A"].width = 100

    wb.save(path)
    return path
