"""STUB: Ingestion configuration constants.

Minimal definitions to enable imports from ingestion.config.
Full implementation deferred.
"""

# Backfill
INGESTION_BACKFILL_CHUNK_DAYS: int = 30
INGESTION_BACKFILL_DAYS: int = 365

# Batch / delay
INGESTION_BATCH_DELAY_S: float = 2.0
INGESTION_BATCH_SIZE_UFS: int = 5
INGESTION_CONCURRENT_UFS: int = 5
INGESTION_DATE_RANGE_DAYS: int = 90
INGESTION_INCREMENTAL_DAYS: int = 7
INGESTION_MAX_PAGES: int = 5
INGESTION_MODALIDADES: list[int] = None  # type: ignore[assignment]

# Upsert
INGESTION_PURGE_GRACE_DAYS: int = 30
INGESTION_UPSERT_BATCH_SIZE: int = 500
INGESTION_UFS: list[str] = None  # type: ignore[assignment]

# ARP
INGESTION_ARP_DAYS: int = 90
INGESTION_ARP_ENABLED: bool = True
INGESTION_ARP_MAX_PAGES: int = 100

# PCA
INGESTION_PCA_ENABLED: bool = True
INGESTION_PCA_MAX_PAGES: int = 100

__all__ = [
    "INGESTION_BACKFILL_CHUNK_DAYS",
    "INGESTION_BACKFILL_DAYS",
    "INGESTION_BATCH_DELAY_S",
    "INGESTION_BATCH_SIZE_UFS",
    "INGESTION_CONCURRENT_UFS",
    "INGESTION_DATE_RANGE_DAYS",
    "INGESTION_INCREMENTAL_DAYS",
    "INGESTION_MAX_PAGES",
    "INGESTION_MODALIDADES",
    "INGESTION_PURGE_GRACE_DAYS",
    "INGESTION_UPSERT_BATCH_SIZE",
    "INGESTION_UFS",
    "INGESTION_ARP_DAYS",
    "INGESTION_ARP_ENABLED",
    "INGESTION_ARP_MAX_PAGES",
    "INGESTION_PCA_ENABLED",
    "INGESTION_PCA_MAX_PAGES",
]
