"""STUB: Ingestion Prometheus metrics constants.

Minimal definitions to enable imports from ingestion.metrics.
Full implementation deferred.
"""

# Shared
INGESTION_PAGES_FETCHED = None
INGESTION_RECORDS_FETCHED = None
INGESTION_RECORDS_UPSERTED = None
INGESTION_RUN_DURATION = None
INGESTION_UFS_FAILED = None
INGESTION_UFS_PROCESSED = None

# ARP
ARP_PAGES_FETCHED = None
ARP_RECORDS_FETCHED = None
ARP_RECORDS_UPSERTED = None
ARP_RUN_DURATION = None
ARP_RUNS_TOTAL = None

# PCA
PCA_PAGES_FETCHED = None
PCA_RECORDS_FETCHED = None
PCA_RECORDS_UPSERTED = None
PCA_RUN_DURATION = None
PCA_RUNS_TOTAL = None

__all__ = [
    "INGESTION_PAGES_FETCHED",
    "INGESTION_RECORDS_FETCHED",
    "INGESTION_RECORDS_UPSERTED",
    "INGESTION_RUN_DURATION",
    "INGESTION_UFS_FAILED",
    "INGESTION_UFS_PROCESSED",
    "ARP_PAGES_FETCHED",
    "ARP_RECORDS_FETCHED",
    "ARP_RECORDS_UPSERTED",
    "ARP_RUN_DURATION",
    "ARP_RUNS_TOTAL",
    "PCA_PAGES_FETCHED",
    "PCA_RECORDS_FETCHED",
    "PCA_RECORDS_UPSERTED",
    "PCA_RUN_DURATION",
    "PCA_RUNS_TOTAL",
]
