"""Reajuste em sentido estrito — Lei nº 14.133/2021.

Capacidade comercial para identificar, classificar e consolidar contratos
públicos de construção civil potencialmente aptos a reajuste periódico por
índice contratual (NÃO reequilíbrio, repactuação, atualização por atraso ou
aditivo quantitativo).
"""

from __future__ import annotations

MODULE_VERSION = "1.0.0"
CAMPAIGN_SLUG = "reajuste_14133"
DEFAULT_AS_OF = "2026-08-04"
DEFAULT_OUTPUT_ROOT = "output/commercial/reajuste_14133"

# Status de elegibilidade (funil fail-closed)
STATUS_HOT_VERIFIED = "HOT_VERIFIED"
STATUS_STRONG_CANDIDATE = "STRONG_CANDIDATE"
STATUS_REVIEW_REQUIRED = "REVIEW_REQUIRED"
STATUS_RESEARCH_REQUIRED = "RESEARCH_REQUIRED"
STATUS_ALREADY_ADJUSTED = "ALREADY_ADJUSTED"
STATUS_NOT_ELIGIBLE = "NOT_ELIGIBLE"
STATUS_LEGAL_REGIME_UNKNOWN = "LEGAL_REGIME_UNKNOWN"
STATUS_CLOSED = "CLOSED_OR_FINANCIALLY_EXHAUSTED"

ELIGIBILITY_STATUSES = (
    STATUS_HOT_VERIFIED,
    STATUS_STRONG_CANDIDATE,
    STATUS_REVIEW_REQUIRED,
    STATUS_RESEARCH_REQUIRED,
    STATUS_ALREADY_ADJUSTED,
    STATUS_NOT_ELIGIBLE,
    STATUS_LEGAL_REGIME_UNKNOWN,
    STATUS_CLOSED,
)

# Rankings
RANKING_NACIONAL = "NACIONAL"
RANKING_SUL_SC = "SUL_SC_PRIORITY"
SUL_UFS = frozenset({"SC", "PR", "RS"})

# Data-base status
DATA_BASE_CONFIRMED = "CONFIRMED"
DATA_BASE_PROXY = "PROXY_PROSPECTION_ONLY"
DATA_BASE_MISSING = "MISSING"

# Finance labels
UPPER_BOUND_LABEL = "UPPER_BOUND_NOT_CLAIM_VALUE"

# Legal regimes
REGIME_14133 = "LEI_14133_2021"
REGIME_8666 = "LEI_8666_1993"
REGIME_10520 = "LEI_10520_2002"
REGIME_RDC = "RDC"
REGIME_UNKNOWN = "UNKNOWN"
REGIME_OTHER = "OTHER"

__all__ = [
    "MODULE_VERSION",
    "CAMPAIGN_SLUG",
    "DEFAULT_AS_OF",
    "DEFAULT_OUTPUT_ROOT",
    "ELIGIBILITY_STATUSES",
    "STATUS_HOT_VERIFIED",
    "STATUS_STRONG_CANDIDATE",
    "STATUS_REVIEW_REQUIRED",
    "STATUS_RESEARCH_REQUIRED",
    "STATUS_ALREADY_ADJUSTED",
    "STATUS_NOT_ELIGIBLE",
    "STATUS_LEGAL_REGIME_UNKNOWN",
    "STATUS_CLOSED",
    "RANKING_NACIONAL",
    "RANKING_SUL_SC",
    "SUL_UFS",
    "DATA_BASE_CONFIRMED",
    "DATA_BASE_PROXY",
    "DATA_BASE_MISSING",
    "UPPER_BOUND_LABEL",
    "REGIME_14133",
    "REGIME_8666",
    "REGIME_10520",
    "REGIME_RDC",
    "REGIME_UNKNOWN",
    "REGIME_OTHER",
]
