"""Reajuste em sentido estrito — Lei nº 14.133/2021.

Capacidade comercial para identificar, classificar e consolidar contratos
públicos de construção civil potencialmente aptos a reajuste periódico por
índice contratual (NÃO reequilíbrio, repactuação, atualização por atraso ou
aditivo quantitativo).

v2: unidade comercial = fornecedor (portfolio); gates de outreach distintos
da classificação jurídica; varredura integral com keyset; prova documental
fail-closed (PDF binário ≠ texto extraído).
"""

from __future__ import annotations

MODULE_VERSION = "3.1.0"
CAMPAIGN_SLUG = "reajuste_14133"
DEFAULT_AS_OF = "2026-08-04"
DEFAULT_OUTPUT_ROOT = "output/commercial/reajuste_14133"

# ---------------------------------------------------------------------------
# Commercial funnel stages (v3) — multi-dimensional, not binary claim gates
# ---------------------------------------------------------------------------
POTENTIAL_ADJUSTMENT_SIGNAL = "POTENTIAL_ADJUSTMENT_SIGNAL"
LIKELY_ADJUSTMENT_OPPORTUNITY = "LIKELY_ADJUSTMENT_OPPORTUNITY"
DIAGNOSTIC_OUTREACH_READY = "DIAGNOSTIC_OUTREACH_READY"
DOCUMENT_REQUEST_READY = "DOCUMENT_REQUEST_READY"
VERIFIED_ADJUSTMENT_OPPORTUNITY = "VERIFIED_ADJUSTMENT_OPPORTUNITY"
CALCULABLE_ADJUSTMENT_CLAIM = "CALCULABLE_ADJUSTMENT_CLAIM"

COMMERCIAL_STAGES = (
    POTENTIAL_ADJUSTMENT_SIGNAL,
    LIKELY_ADJUSTMENT_OPPORTUNITY,
    DIAGNOSTIC_OUTREACH_READY,
    DOCUMENT_REQUEST_READY,
    VERIFIED_ADJUSTMENT_OPPORTUNITY,
    CALCULABLE_ADJUSTMENT_CLAIM,
)

# Temporal evidence hierarchy (A exact → D insufficient)
TEMPORAL_LEVEL_A = "A_EXACT_BUDGET_DATE"
TEMPORAL_LEVEL_B = "B_CONSERVATIVE_SIGNATURE_GT_12M"
TEMPORAL_LEVEL_C = "C_PROXY_PROBABLE"
TEMPORAL_LEVEL_D = "D_INSUFFICIENT"

TEMPORAL_LEVELS = (
    TEMPORAL_LEVEL_A,
    TEMPORAL_LEVEL_B,
    TEMPORAL_LEVEL_C,
    TEMPORAL_LEVEL_D,
)

# Status de elegibilidade jurídica/documental (funil fail-closed)
STATUS_HOT_VERIFIED = "HOT_VERIFIED"
STATUS_STRONG_CANDIDATE = "STRONG_CANDIDATE"
STATUS_REVIEW_REQUIRED = "REVIEW_REQUIRED"
STATUS_RESEARCH_REQUIRED = "RESEARCH_REQUIRED"
STATUS_ALREADY_ADJUSTED = "ALREADY_ADJUSTED"
STATUS_NOT_ELIGIBLE = "NOT_ELIGIBLE"
STATUS_LEGAL_REGIME_UNKNOWN = "LEGAL_REGIME_UNKNOWN"
STATUS_LEGAL_REGIME_CONFLICT = "LEGAL_REGIME_CONFLICT"
STATUS_CLOSED = "CLOSED_OR_FINANCIALLY_EXHAUSTED"

ELIGIBILITY_STATUSES = (
    STATUS_HOT_VERIFIED,
    STATUS_STRONG_CANDIDATE,
    STATUS_REVIEW_REQUIRED,
    STATUS_RESEARCH_REQUIRED,
    STATUS_ALREADY_ADJUSTED,
    STATUS_NOT_ELIGIBLE,
    STATUS_LEGAL_REGIME_UNKNOWN,
    STATUS_LEGAL_REGIME_CONFLICT,
    STATUS_CLOSED,
)

# Gates comerciais de abordagem (distintos da classificação jurídica)
OUTREACH_READY = "OUTREACH_READY"
OUTREACH_READY_WITHOUT_VALUE_ESTIMATE = "OUTREACH_READY_WITHOUT_VALUE_ESTIMATE"
TECHNICALLY_VERIFIED_PENDING_TIAGO = "TECHNICALLY_VERIFIED_PENDING_TIAGO"
DOCUMENT_REQUEST_CANDIDATE = "DOCUMENT_REQUEST_CANDIDATE"
NOT_READY_FOR_OUTREACH = "NOT_READY_FOR_OUTREACH"

OUTREACH_STATUSES = (
    OUTREACH_READY,
    OUTREACH_READY_WITHOUT_VALUE_ESTIMATE,
    TECHNICALLY_VERIFIED_PENDING_TIAGO,
    DOCUMENT_REQUEST_CANDIDATE,
    NOT_READY_FOR_OUTREACH,
)

# Document ↔ contract binding
DOCUMENT_LINK_VERIFIED = "DOCUMENT_LINK_VERIFIED"
DOCUMENT_LINK_PARTIAL = "DOCUMENT_LINK_PARTIAL"
DOCUMENT_LINK_CONFLICT = "DOCUMENT_LINK_CONFLICT"
DOCUMENT_LINK_UNVERIFIED = "DOCUMENT_LINK_UNVERIFIED"

DOCUMENT_LINK_STATES = (
    DOCUMENT_LINK_VERIFIED,
    DOCUMENT_LINK_PARTIAL,
    DOCUMENT_LINK_CONFLICT,
    DOCUMENT_LINK_UNVERIFIED,
)

# Document pipeline states
DOC_URL_LOCATED = "DOCUMENT_URL_LOCATED"
DOC_DOWNLOADED = "DOCUMENT_DOWNLOADED"
DOC_TEXT_EXTRACTED = "TEXT_EXTRACTED"
DOC_CLAUSE_LOCATED = "CLAUSE_LOCATED"
DOC_CLAUSE_HUMAN_CONFIRMED = "CLAUSE_HUMAN_CONFIRMED"
DOC_UNAVAILABLE = "DOCUMENT_UNAVAILABLE"
DOC_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"

DOCUMENT_PIPELINE_STATES = (
    DOC_URL_LOCATED,
    DOC_DOWNLOADED,
    DOC_TEXT_EXTRACTED,
    DOC_CLAUSE_LOCATED,
    DOC_CLAUSE_HUMAN_CONFIRMED,
    DOC_UNAVAILABLE,
    DOC_PARSE_FAILED,
)

# Temporal layers
TEMPORAL_CANDIDATE_BY_PROXY = "TEMPORAL_CANDIDATE_BY_PROXY"
TEMPORAL_ELIGIBILITY_CONFIRMED = "TEMPORAL_ELIGIBILITY_CONFIRMED"
TEMPORAL_INCOMPLETE = "TEMPORAL_INCOMPLETE"
TEMPORAL_UNKNOWN = "TEMPORAL_UNKNOWN"

# Adjustment history
NO_PRIOR_ADJUSTMENT_LOCATED = "NO_PRIOR_ADJUSTMENT_LOCATED"
PRIOR_ADJUSTMENT_CONFIRMED = "PRIOR_ADJUSTMENT_CONFIRMED"
PARTIAL_ADJUSTMENT_CONFIRMED = "PARTIAL_ADJUSTMENT_CONFIRMED"
ADJUSTMENT_HISTORY_CONFLICT = "ADJUSTMENT_HISTORY_CONFLICT"
ADJUSTMENT_HISTORY_UNAVAILABLE = "ADJUSTMENT_HISTORY_UNAVAILABLE"

# Execution status
CONTRACT_ACTIVE = "CONTRACT_ACTIVE"
CONTRACT_EXPIRED_WITH_OPEN_FINANCIAL_OBLIGATIONS = "CONTRACT_EXPIRED_WITH_OPEN_FINANCIAL_OBLIGATIONS"
CONTRACT_FULLY_MEASURED = "CONTRACT_FULLY_MEASURED"
CONTRACT_CLOSED = "CONTRACT_CLOSED"
EXECUTION_STATUS_UNKNOWN = "EXECUTION_STATUS_UNKNOWN"

# Value quality
VALUE_CONFIRMED = "VALUE_CONFIRMED"
VALUE_PLAUSIBLE = "VALUE_PLAUSIBLE"
VALUE_OUTLIER_REQUIRES_REVIEW = "VALUE_OUTLIER_REQUIRES_REVIEW"
VALUE_CONFLICT = "VALUE_CONFLICT"
VALUE_UNUSABLE = "VALUE_UNUSABLE"

# Rankings
RANKING_NACIONAL = "NACIONAL"
RANKING_SUL_SC = "SUL_SC_PRIORITY"
SUL_UFS = frozenset({"SC", "PR", "RS"})

# Data-base status
DATA_BASE_CONFIRMED = "CONFIRMED"
DATA_BASE_PROXY = "PROXY_PROSPECTION_ONLY"
DATA_BASE_MISSING = "MISSING"

# Finance labels
UPPER_BOUND_LABEL = "UPPER_BOUND_NOT_CLAIM_VALUE"

# Legal regimes (evidence hierarchy R-A…R-X — never year/PNCP alone)
REGIME_14133 = "LEI_14133_2021"  # R-A proven (export alias: LEI_14133_PROVEN)
REGIME_LIKELY_14133 = "LIKELY_14133"  # R-B strongly indicated, not proven
REGIME_TRANSITIONAL_UNRESOLVED = "TRANSITIONAL_REGIME_UNRESOLVED"  # R-C
REGIME_8666 = "LEI_8666_1993"
REGIME_10520 = "LEI_10520_2002"
REGIME_RDC = "RDC"
REGIME_UNKNOWN = "UNKNOWN"  # R-D
REGIME_OTHER = "OTHER"
REGIME_CONFLICT = "LEGAL_REGIME_CONFLICT"  # R-X (export label: REGIME_CONFLICT)

# Regime evidence levels
EVIDENCE_LEVEL_RA = "R-A"
EVIDENCE_LEVEL_RB = "R-B"
EVIDENCE_LEVEL_RC = "R-C"
EVIDENCE_LEVEL_RD = "R-D"
EVIDENCE_LEVEL_RX = "R-X"

# Legal confidence labels (commercial dimensions)
LEGAL_CONF_HIGH = "high"
LEGAL_CONF_MEDIUM = "medium"
LEGAL_CONF_LOW = "low"
LEGAL_CONF_NONE = "none"
LEGAL_CONF_UNRESOLVED = "unresolved"
LEGAL_CONF_CONFLICT = "conflict"

# Dual-regime transition (Lei 14.133 optional until 2023-12-30)
TRANSITION_START_YEAR = 2021
TRANSITION_END_YEAR = 2023
# Signatures shortly after transition may still stem from legacy processes
POST_TRANSITION_AMBIGUITY_YEAR = 2024

# Terminal campaign statuses
TERMINAL_SUCCESS_OUTREACH = "SUCCESS_VERIFIED_OUTREACH_LEADS"
TERMINAL_BLOCKED_INSUFFICIENT = "BLOCKED_INSUFFICIENT_VERIFIED_OUTREACH_LEADS"

__all__ = [
    "MODULE_VERSION",
    "CAMPAIGN_SLUG",
    "DEFAULT_AS_OF",
    "DEFAULT_OUTPUT_ROOT",
    "POTENTIAL_ADJUSTMENT_SIGNAL",
    "LIKELY_ADJUSTMENT_OPPORTUNITY",
    "DIAGNOSTIC_OUTREACH_READY",
    "DOCUMENT_REQUEST_READY",
    "VERIFIED_ADJUSTMENT_OPPORTUNITY",
    "CALCULABLE_ADJUSTMENT_CLAIM",
    "COMMERCIAL_STAGES",
    "TEMPORAL_LEVEL_A",
    "TEMPORAL_LEVEL_B",
    "TEMPORAL_LEVEL_C",
    "TEMPORAL_LEVEL_D",
    "TEMPORAL_LEVELS",
    "ELIGIBILITY_STATUSES",
    "STATUS_HOT_VERIFIED",
    "STATUS_STRONG_CANDIDATE",
    "STATUS_REVIEW_REQUIRED",
    "STATUS_RESEARCH_REQUIRED",
    "STATUS_ALREADY_ADJUSTED",
    "STATUS_NOT_ELIGIBLE",
    "STATUS_LEGAL_REGIME_UNKNOWN",
    "STATUS_LEGAL_REGIME_CONFLICT",
    "STATUS_CLOSED",
    "OUTREACH_READY",
    "OUTREACH_READY_WITHOUT_VALUE_ESTIMATE",
    "TECHNICALLY_VERIFIED_PENDING_TIAGO",
    "DOCUMENT_REQUEST_CANDIDATE",
    "NOT_READY_FOR_OUTREACH",
    "OUTREACH_STATUSES",
    "DOCUMENT_LINK_VERIFIED",
    "DOCUMENT_LINK_PARTIAL",
    "DOCUMENT_LINK_CONFLICT",
    "DOCUMENT_LINK_UNVERIFIED",
    "DOCUMENT_LINK_STATES",
    "DOC_URL_LOCATED",
    "DOC_DOWNLOADED",
    "DOC_TEXT_EXTRACTED",
    "DOC_CLAUSE_LOCATED",
    "DOC_CLAUSE_HUMAN_CONFIRMED",
    "DOC_UNAVAILABLE",
    "DOC_PARSE_FAILED",
    "DOCUMENT_PIPELINE_STATES",
    "TEMPORAL_CANDIDATE_BY_PROXY",
    "TEMPORAL_ELIGIBILITY_CONFIRMED",
    "TEMPORAL_INCOMPLETE",
    "TEMPORAL_UNKNOWN",
    "NO_PRIOR_ADJUSTMENT_LOCATED",
    "PRIOR_ADJUSTMENT_CONFIRMED",
    "PARTIAL_ADJUSTMENT_CONFIRMED",
    "ADJUSTMENT_HISTORY_CONFLICT",
    "ADJUSTMENT_HISTORY_UNAVAILABLE",
    "CONTRACT_ACTIVE",
    "CONTRACT_EXPIRED_WITH_OPEN_FINANCIAL_OBLIGATIONS",
    "CONTRACT_FULLY_MEASURED",
    "CONTRACT_CLOSED",
    "EXECUTION_STATUS_UNKNOWN",
    "VALUE_CONFIRMED",
    "VALUE_PLAUSIBLE",
    "VALUE_OUTLIER_REQUIRES_REVIEW",
    "VALUE_CONFLICT",
    "VALUE_UNUSABLE",
    "RANKING_NACIONAL",
    "RANKING_SUL_SC",
    "SUL_UFS",
    "DATA_BASE_CONFIRMED",
    "DATA_BASE_PROXY",
    "DATA_BASE_MISSING",
    "UPPER_BOUND_LABEL",
    "REGIME_14133",
    "REGIME_LIKELY_14133",
    "REGIME_TRANSITIONAL_UNRESOLVED",
    "REGIME_8666",
    "REGIME_10520",
    "REGIME_RDC",
    "REGIME_UNKNOWN",
    "REGIME_OTHER",
    "REGIME_CONFLICT",
    "EVIDENCE_LEVEL_RA",
    "EVIDENCE_LEVEL_RB",
    "EVIDENCE_LEVEL_RC",
    "EVIDENCE_LEVEL_RD",
    "EVIDENCE_LEVEL_RX",
    "LEGAL_CONF_HIGH",
    "LEGAL_CONF_MEDIUM",
    "LEGAL_CONF_LOW",
    "LEGAL_CONF_NONE",
    "LEGAL_CONF_UNRESOLVED",
    "LEGAL_CONF_CONFLICT",
    "TRANSITION_START_YEAR",
    "TRANSITION_END_YEAR",
    "POST_TRANSITION_AMBIGUITY_YEAR",
    "TERMINAL_SUCCESS_OUTREACH",
    "TERMINAL_BLOCKED_INSUFFICIENT",
]
