"""CLI entry: python3 -m scripts.commercial.reajuste_14133"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from scripts.commercial.reajuste_14133 import DEFAULT_AS_OF, DEFAULT_OUTPUT_ROOT, MODULE_VERSION
from scripts.commercial.reajuste_14133.desk_review import write_automated_triage
from scripts.commercial.reajuste_14133.export.excel_export import export_workbook
from scripts.commercial.reajuste_14133.export.reports import (
    assert_no_secrets,
    write_csv_json,
    write_data_quality,
    write_dossiers,
    write_executive_brief,
    write_methodology,
)
from scripts.commercial.reajuste_14133.pipeline import run_pipeline


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="python3 -m scripts.commercial.reajuste_14133",
        description=(
            "Fila comercial CONFENGE: reajuste em sentido estrito (Lei 14.133/2021). "
            "Não cobre reequilíbrio, repactuação, atualização por atraso ou aditivo quantitativo."
        ),
    )
    p.add_argument("--as-of", default=DEFAULT_AS_OF, help="Data de referência (YYYY-MM-DD)")
    p.add_argument(
        "--scope",
        default="national",
        choices=("national", "sul_sc", "sc"),
        help="Escopo geográfico do pré-filtro SQL",
    )
    p.add_argument("--uf", default=None, help="Filtrar UF (ex.: SC)")
    p.add_argument("--municipio", default=None, help="Filtrar município (ILIKE)")
    p.add_argument("--supplier-cnpj", default=None, help="Filtrar CNPJ fornecedor")
    p.add_argument("--min-contract-value", type=float, default=1_000_000.0)
    p.add_argument("--min-potential-value", type=float, default=None)
    p.add_argument("--status", default=None, help="Filtrar status de elegibilidade")
    p.add_argument("--top", type=int, default=200)
    p.add_argument("--verify-documents", action="store_true")
    p.add_argument("--max-document-fetches", type=int, default=30)
    p.add_argument("--enrich-contacts", action="store_true")
    p.add_argument("--max-contact-lookups", type=int, default=40)
    p.add_argument("--output-dir", default=None, help="Default: output/commercial/reajuste_14133/<as-of>/")
    p.add_argument("--dsn", default=None, help="DSN read-only (env REAJUSTE_SOURCE_DSN / LOCAL_DATALAKE_DSN)")
    p.add_argument("--ssh", action="store_true", help="Forçar leitura via SSH ec-prod (read-only)")
    p.add_argument("--csv", default=None, help="Fonte CSV alternativa (ex.: artifacts/outreach/...)")
    p.add_argument("--max-source-rows", type=int, default=25000)
    p.add_argument("--batch-size", type=int, default=2000)
    p.add_argument("--export-all", action="store_true", help="Gerar XLSX/CSV/JSON/docs/dossiers")
    p.add_argument("--dossier-count", type=int, default=30)
    p.add_argument("--strict", action="store_true", help="Exit != 0 se secrets nos artefatos ou falha de pipeline")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--json", action="store_true", help="Imprimir resumo JSON em stdout")
    p.add_argument(
        "--manual-review",
        action="store_true",
        help=(
            "Gerar automated_object_triage.json (máquina). "
            "Revisão humana canônica: human_desk_review_top30.md (artefato estático por campanha)."
        ),
    )
    p.add_argument(
        "--resume-from",
        default=None,
        help="Diretório de run com .checkpoint/ para retomar após falha",
    )
    p.add_argument(
        "--checkpoint-dir",
        default=None,
        help="Gravar checkpoint neste diretório (default: --output-dir quando exporta)",
    )
    return p


def export_run(run: dict[str, Any], out_dir: Path, *, dossier_count: int, manual_review: bool) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = write_csv_json(out_dir, run)
    paths["methodology"] = str(write_methodology(out_dir))
    paths["data_quality"] = str(write_data_quality(out_dir, run))
    review_for_brief: list[dict[str, Any]] | None = None
    if manual_review:
        triage_meta = write_automated_triage(out_dir, run.get("top_leads") or [])
        paths.update(triage_meta.get("paths") or {})
        run.setdefault("metrics", {}).update(
            {
                "automated_object_triage_count": triage_meta.get("automated_object_triage_count"),
                "manual_review_note": (
                    "automated_object_triage.json = MACHINE ONLY. "
                    "Human review (if present) is human_desk_review_top30.md/json — "
                    "hand-authored per campaign, never regenerated by this CLI flag."
                ),
            }
        )
        # Prefer hand-authored human review for the brief when available
        human_path = out_dir / "human_desk_review_top30.json"
        manual_path = out_dir / "manual_review.json"
        for candidate in (human_path, manual_path):
            if not candidate.exists():
                continue
            try:
                payload = json.loads(candidate.read_text(encoding="utf-8"))
                if payload.get("kind") == "human_desk_review" and payload.get("reviews"):
                    review_for_brief = payload["reviews"]
                    paths["human_desk_review"] = str(candidate)
                    run["metrics"]["human_desk_review_count"] = payload.get("n")
                    run["metrics"]["human_desk_review_false_positives"] = payload.get(
                        "false_positives"
                    )
                    run["metrics"]["human_desk_review_kept_in_queue"] = payload.get(
                        "kept_in_queue"
                    )
                    run["metrics"]["human_desk_review_keep_rate"] = payload.get("keep_rate")
                    break
            except (OSError, json.JSONDecodeError):
                continue
    paths["executive_brief"] = str(write_executive_brief(out_dir, run, review_for_brief))
    paths["xlsx"] = str(export_workbook(out_dir, run))
    dpaths = write_dossiers(out_dir, run.get("top_leads") or [], n=dossier_count)
    paths["dossiers_count"] = str(len(dpaths))
    man = out_dir / "run_manifest.json"
    try:
        data = json.loads(man.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        data = {}
    data["artifact_paths"] = paths
    data["metrics"] = run.get("metrics")
    data["resumed"] = run.get("resumed")
    data["checkpoint_dir"] = run.get("checkpoint_dir")
    man.write_text(json.dumps(data, indent=2, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
    secrets = assert_no_secrets(out_dir)
    return {"paths": paths, "secret_hits": secrets}


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    out_dir = Path(
        args.output_dir
        or f"{DEFAULT_OUTPUT_ROOT}/{args.as_of}"
    )
    # Checkpoint under output dir by default when exporting (enables resume)
    ckpt = args.checkpoint_dir or (str(out_dir) if args.export_all else None)
    try:
        run = run_pipeline(
            as_of=args.as_of,
            scope=args.scope,
            uf=args.uf,
            municipio=args.municipio,
            supplier_cnpj=args.supplier_cnpj,
            min_contract_value=args.min_contract_value,
            min_potential_value=args.min_potential_value,
            status_filter=args.status,
            top=args.top,
            verify_documents=args.verify_documents,
            max_document_fetches=args.max_document_fetches,
            enrich_contacts=args.enrich_contacts,
            max_contact_lookups=args.max_contact_lookups,
            dsn=args.dsn,
            prefer_ssh=args.ssh,
            csv_path=args.csv,
            dry_run=args.dry_run,
            batch_size=args.batch_size,
            max_source_rows=args.max_source_rows,
            resume_from=args.resume_from,
            checkpoint_dir=ckpt if not args.resume_from else None,
        )
    except Exception as exc:
        print(f"ERROR: pipeline failed: {exc}", file=sys.stderr)
        if args.strict:
            return 2
        return 1

    export_info: dict[str, Any] = {}
    if args.export_all and not args.dry_run:
        export_info = export_run(
            run,
            out_dir,
            dossier_count=args.dossier_count,
            manual_review=bool(args.manual_review or True),
        )
        if export_info.get("secret_hits"):
            print(
                f"SECURITY: secret-like patterns in {export_info['secret_hits']}",
                file=sys.stderr,
            )
            if args.strict:
                return 3

    summary = {
        "module_version": MODULE_VERSION,
        "run_id": run.get("run_id"),
        "as_of": run.get("as_of"),
        "source_mode": run.get("source_mode"),
        "funnel": run.get("funnel"),
        "metrics": run.get("metrics"),
        "top_preview": [
            {
                "ranking": lead.get("ranking"),
                "classificacao": lead.get("classificacao"),
                "score_total": lead.get("score_total"),
                "uf": lead.get("uf"),
                "cnpj_masked": str(lead.get("cnpj") or "")[:8] + "****",
                "contrato_id": lead.get("contrato_id"),
                "data_base_status": lead.get("data_base_status"),
            }
            for lead in (run.get("top_leads") or [])[:10]
        ],
        "output_dir": str(out_dir) if args.export_all else None,
        "export": export_info.get("paths") if export_info else None,
        "dry_run": run.get("dry_run", False),
    }

    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2, default=str))
    else:
        print(f"reajuste_14133 v{MODULE_VERSION} run={run.get('run_id')}")
        print(f"source={run.get('source_mode')} as_of={run.get('as_of')}")
        funnel = run.get("funnel") or {}
        print(
            "funnel: "
            f"raw={funnel.get('examined_raw')} construction={funnel.get('construction')} "
            f"HOT={funnel.get('HOT_VERIFIED')} STRONG={funnel.get('STRONG_CANDIDATE')} "
            f"REVIEW={funnel.get('REVIEW_REQUIRED')} REGIME_UNK={funnel.get('LEGAL_REGIME_UNKNOWN')}"
        )
        if args.export_all and not args.dry_run:
            print(f"artifacts → {out_dir}")
        for row in summary["top_preview"]:
            print(
                f"  #{row['ranking']} {row['classificacao']} score={row['score_total']} "
                f"{row['uf']} {row['contrato_id']}"
            )

    # Strict: zero construction with successful source is suspicious only if examined_raw==0
    if args.strict and not args.dry_run:
        if (run.get("funnel") or {}).get("examined_raw", 0) == 0:
            print("ERROR: strict mode — zero rows examined from source", file=sys.stderr)
            return 4
        # Ensure no HOT from table-only
        for lead in run.get("leads") or []:
            if lead.get("classificacao") == "HOT_VERIFIED":
                gates = lead.get("hot_gates") or {}
                if not gates.get("documentos_acessiveis") or not gates.get("data_base_exata"):
                    print("ERROR: HOT_VERIFIED without documentary gates", file=sys.stderr)
                    return 5
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
