"""Automated object triage only — NOT a human desk review.

Human review for campaign runs is a **static, hand-written** artifact:
``human_desk_review_top30.md`` / ``human_desk_review_top30.json`` under the
run output directory. Those files are authored by inspecting each lead's
objeto + PNCP URL + values; they are not regenerated by this module.

This module only emits ``automated_object_triage.json`` (machine flags).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def automated_object_triage(leads: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Machine-only object/regime flags. Never call this 'operator' or 'human'."""
    rows: list[dict[str, Any]] = []
    for lead in leads[:30]:
        notes: list[str] = []
        flags: list[str] = []
        obj = (lead.get("objeto") or "").lower()
        if any(
            x in obj
            for x in (
                "fornecimento de gás",
                "fornecimento de gas",
                "software",
                "licenciamento de software",
                "limpeza predial",
                "gestão operacional",
                "gestao operacional",
                "tecnologia e servicos em saude",
                "tecnologia e serviços em saúde",
                "suporte logístico",
                "suporte logistico",
                "motores da fabricante",
            )
        ):
            flags.append("possible_non_construction_object")
            notes.append("Objeto com vocabulário de serviço não-obra / TI / saúde / logística")
        if "parceria público-privada" in obj or "parceria publico-privada" in obj or "concessão administrativa" in obj:
            flags.append("ppp_or_concession")
            notes.append("PPP/concessão — reajuste de obra pode existir, mas ICP comercial é mais fraco")
        if lead.get("data_base_status") != "CONFIRMED":
            flags.append("data_base_not_confirmed")
            notes.append("data_base proxy/missing — bloqueia HOT_VERIFIED")
        if not lead.get("regime_proven"):
            flags.append("regime_unproven")
            notes.append("regime 14.133 não comprovado")
        if lead.get("classificacao") == "HOT_VERIFIED":
            gates = lead.get("hot_gates") or {}
            if not all(gates.values()) if gates else True:
                flags.append("hot_without_gates")
                notes.append("HOT_VERIFIED sem 10 gates — erro de pipeline")
        rows.append(
            {
                "kind": "automated_object_triage",
                "contrato_id": lead.get("contrato_id"),
                "cnpj_masked": str(lead.get("cnpj") or "")[:8] + "****",
                "classificacao": lead.get("classificacao"),
                "score": lead.get("score_total"),
                "flags": flags,
                "notes": notes,
                "urls": lead.get("urls_oficiais") or [],
                "label": "MACHINE_ONLY_NOT_HUMAN_REVIEW",
            }
        )
    return rows


# Back-compat aliases (deprecated names)
automated_precheck = automated_object_triage


def write_automated_triage(out_dir: Path, leads: list[dict[str, Any]]) -> dict[str, Any]:
    """Write machine triage only. Does not create or overwrite human_desk_review_*."""
    out_dir.mkdir(parents=True, exist_ok=True)
    triage = automated_object_triage(leads)
    path = out_dir / "automated_object_triage.json"
    path.write_text(
        json.dumps(
            {
                "kind": "automated_object_triage",
                "disclaimer": (
                    "MACHINE ONLY. Not desk review. Not operator review. "
                    "Human review lives in human_desk_review_top30.md when present."
                ),
                "n": len(triage),
                "rows": triage,
            },
            indent=2,
            ensure_ascii=False,
            default=str,
        )
        + "\n",
        encoding="utf-8",
    )
    # keep old filename as copy for tools that still look for it
    (out_dir / "automated_precheck.json").write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    return {
        "automated_object_triage_count": len(triage),
        "paths": {
            "automated_object_triage": str(path),
            "automated_precheck": str(out_dir / "automated_precheck.json"),
        },
        "human_review_note": (
            "If human_desk_review_top30.md exists in this directory, it is the "
            "authoritative manual review. This module never regenerates it."
        ),
    }


# Deprecated: do not use for campaign claims of human review
def write_desk_review_artifacts(out_dir: Path, leads: list[dict[str, Any]]) -> dict[str, Any]:
    """Deprecated name — only writes automated triage; never claims operator review."""
    return write_automated_triage(out_dir, leads)
