"""Pure outreach claim policy package (``CLAIM_POLICY``).

Consumes ``scripts/contracts_truth.py`` as the single lifecycle authority. Never
imports ``confenge_account_intelligence`` or ``confenge_contact_resolution``.
"""

from __future__ import annotations

from scripts.confenge_claim_policy.policy import (
    ALLOWED_TENSES,
    CLAIM_MODE_NONE,
    CLAIM_MODES,
    CLAIM_POLICY_VERSION,
    CONTEMPORARY_EVENT_DAYS,
    COPY_HASH_PREFIX,
    CURRENT_ACTIONABLE,
    CURRENT_CONTRACT,
    DO_NOT_CITE,
    HISTORICAL_CONTEXT,
    HISTORICAL_CONTRACT,
    NEUTRAL_FACTUAL,
    OUTREACH_USE_CLASSES,
    PAST_ONLY,
    PRESENT_CONFIRMED,
    PURPOSE_WHY_NOW,
    PURPOSE_WHY_YOU,
    PURPOSES,
    RAW_STATUS_FALLBACK_STATES,
    REASON_RAW_STATUS_NOT_PROMOTABLE,
    RECENT_RETROSPECTIVE,
    RECENT_RETROSPECTIVE_DAYS,
    TENSE_NONE,
    ClaimCandidate,
    ClaimPolicyResult,
    LifecycleResolution,
    MessageClaimSelection,
    allows_present_tense,
    compute_copy_hash,
    demote_to_historical,
    evaluate_claim_policy,
    is_contemporary_event,
    is_tense_permitted,
    normalize_lifecycle_state,
    resolve_lifecycle_state,
    select_message_claims,
)

__all__ = [
    "ALLOWED_TENSES",
    "CLAIM_MODES",
    "CLAIM_MODE_NONE",
    "CLAIM_POLICY_VERSION",
    "CONTEMPORARY_EVENT_DAYS",
    "COPY_HASH_PREFIX",
    "CURRENT_ACTIONABLE",
    "CURRENT_CONTRACT",
    "DO_NOT_CITE",
    "HISTORICAL_CONTEXT",
    "HISTORICAL_CONTRACT",
    "NEUTRAL_FACTUAL",
    "OUTREACH_USE_CLASSES",
    "PAST_ONLY",
    "PRESENT_CONFIRMED",
    "PURPOSES",
    "PURPOSE_WHY_NOW",
    "PURPOSE_WHY_YOU",
    "RAW_STATUS_FALLBACK_STATES",
    "REASON_RAW_STATUS_NOT_PROMOTABLE",
    "RECENT_RETROSPECTIVE",
    "RECENT_RETROSPECTIVE_DAYS",
    "TENSE_NONE",
    "ClaimCandidate",
    "ClaimPolicyResult",
    "LifecycleResolution",
    "MessageClaimSelection",
    "allows_present_tense",
    "compute_copy_hash",
    "demote_to_historical",
    "evaluate_claim_policy",
    "is_contemporary_event",
    "is_tense_permitted",
    "normalize_lifecycle_state",
    "resolve_lifecycle_state",
    "select_message_claims",
]
