#!/usr/bin/env python3
"""Pin the whole CONFENGE outbound chain to one immutable release.

The chain is autonomous by design:

    pncp-contracts.timer
      -> pncp-contracts.service
        OnSuccess -> extra-confenge-source-freshness-gate.service
          OnSuccess -> extra-confenge-target-fit-reconcile.service
            OnSuccess -> extra-confenge-contact-cycle.service
              OnSuccess -> extra-confenge-feed-cycle.service

Every link must run the *same* code. Hand-written ``90-immutable-release.conf``
drop-ins drifted apart (three different SHAs across the chain at once), which is
exactly the unversioned manual configuration this repository must not depend on.

This tool derives each drop-in mechanically from the versioned unit files in
``deploy/systemd`` by rewriting the ``/opt/extra-consultoria`` prefix to the
requested immutable release, applies the whole set atomically-or-not-at-all, and
enables the safety-net timers so a failed chain still retries on its own.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIT_SOURCE = REPO_ROOT / "deploy" / "systemd"

CANONICAL_PREFIX = "/opt/extra-consultoria"
RELEASE_ROOT = Path("/opt/extra-consultoria-releases")
DROPIN_NAME = "90-immutable-release.conf"
SYSTEMD_ROOT = Path("/etc/systemd/system")

FULL_SHA = re.compile(r"^[0-9a-f]{40}$")

# Every unit that executes CONFENGE outbound code. Instance units are pinned
# through their template so all instances follow one release.
CHAIN_UNITS = (
    "pncp-contracts.service",
    "extra-confenge-source-freshness-gate.service",
    "extra-confenge-target-fit-reconcile.service",
    "extra-confenge-target-fit-refresh.service",
    "extra-confenge-target-fit-worker.service",
    "extra-confenge-contact-cycle.service",
    "extra-confenge-feed-cycle.service",
    "extra-confenge-feed-monitor.service",
)

# Timers that must survive a reboot for the chain to run without an operator.
# The OnSuccess chain is the primary path; these are the recovery net for a
# failed or missed link. Concurrency is already guarded by flock in the units.
CHAIN_TIMERS = (
    "pncp-contracts.timer",
    "extra-confenge-target-fit-reconcile.timer",
    "extra-confenge-target-fit-refresh.timer",
    "extra-confenge-contact-cycle.timer",
    "extra-confenge-feed-cycle.timer",
    "extra-confenge-feed-monitor.timer",
)

# Long-running workers that must come back after a reboot.
CHAIN_ENABLED_SERVICES = ("extra-confenge-target-fit-worker.service",)

PINNED_DIRECTIVES = ("WorkingDirectory=", "Environment=PYTHONPATH=", "ExecStart=")


class PinError(RuntimeError):
    """A pin was refused before anything on the host changed."""


def _logical_lines(text: str) -> list[str]:
    """Join systemd line continuations so a multi-line ExecStart stays one unit."""
    lines: list[str] = []
    buffer = ""
    for raw in text.splitlines():
        stripped = raw.rstrip()
        if stripped.endswith("\\"):
            buffer += stripped[:-1].rstrip() + " "
            continue
        lines.append((buffer + stripped.strip()) if buffer else stripped)
        buffer = ""
    if buffer:
        lines.append(buffer.strip())
    return lines


def render_dropin(unit_text: str, sha: str) -> str:
    """Build the drop-in that re-points one unit at an immutable release."""
    release = f"{RELEASE_ROOT}/{sha}"
    directives: list[str] = []
    exec_start: str | None = None
    for line in _logical_lines(unit_text):
        if not any(line.startswith(prefix) for prefix in PINNED_DIRECTIVES):
            continue
        rewritten = line.replace(CANONICAL_PREFIX, release)
        if line.startswith("ExecStart="):
            exec_start = rewritten
        else:
            directives.append(rewritten)
    if exec_start is None:
        raise PinError("unit has no ExecStart to pin")
    if CANONICAL_PREFIX in exec_start.replace(release, ""):
        raise PinError(f"unpinned {CANONICAL_PREFIX} path survived rewriting: {exec_start}")
    body = [
        "# GENERATED by deploy/confenge/pin_release.py. DO NOT EDIT.",
        "# Source of truth: deploy/systemd/<unit> at the pinned release.",
        f"# Immutable release: {sha}",
        "[Service]",
        *directives,
        f"Environment=EXTRA_DEPLOYED_SHA={sha}",
        f"Environment=EXTRA_CODE_SHA={sha}",
        # Clear the inherited ExecStart before appending the pinned one.
        "ExecStart=",
        exec_start,
    ]
    return "\n".join(body) + "\n"


def _run(argv: list[str], *, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(argv, check=check, text=True, capture_output=True, timeout=120)  # noqa: S603


def plan(sha: str) -> dict[str, str]:
    """Render every drop-in up front so a bad unit aborts before any write."""
    if not FULL_SHA.fullmatch(sha):
        raise PinError(f"a full 40-character release SHA is required, got {sha!r}")
    release = RELEASE_ROOT / sha
    if not release.is_dir():
        raise PinError(f"release directory does not exist: {release}")
    if not (release / ".venv" / "bin" / "python").is_file():
        raise PinError(f"release has no interpreter: {release}/.venv/bin/python")
    rendered: dict[str, str] = {}
    for unit in CHAIN_UNITS:
        source = UNIT_SOURCE / unit
        if not source.is_file():
            raise PinError(f"versioned unit file is missing: {source}")
        try:
            rendered[unit] = render_dropin(source.read_text(encoding="utf-8"), sha)
        except PinError as exc:
            raise PinError(f"{unit}: {exc}") from exc
    return rendered


def apply(sha: str, *, dry_run: bool = False) -> dict[str, object]:
    rendered = plan(sha)
    written: list[str] = []
    if not dry_run:
        for unit, body in rendered.items():
            target_dir = SYSTEMD_ROOT / f"{unit}.d"
            target_dir.mkdir(parents=True, exist_ok=True)
            target = target_dir / DROPIN_NAME
            tmp = target.with_suffix(".conf.tmp")
            tmp.write_text(body, encoding="utf-8")
            tmp.replace(target)
            written.append(str(target))
        _run(["systemctl", "daemon-reload"])
        # --now, not just enable: enabling alone writes the wants/ symlink and
        # leaves the timer unloaded until the next boot, which is precisely how
        # the two safety-net timers came to be "enabled" and still absent from
        # `systemctl list-timers`.
        _run(["systemctl", "enable", "--now", *CHAIN_TIMERS])
        _run(["systemctl", "enable", *CHAIN_ENABLED_SERVICES])
    return {
        "schema": "confenge.release_pin.v1",
        "release_sha": sha,
        "units_pinned": list(rendered),
        "timers_enabled": list(CHAIN_TIMERS),
        "services_enabled": list(CHAIN_ENABLED_SERVICES),
        "dropins_written": written,
        "dry_run": dry_run,
    }


def verify(sha: str) -> dict[str, object]:
    """Read back what systemd actually resolved, not what we intended to write."""
    drift: list[dict[str, str]] = []
    for unit in CHAIN_UNITS:
        result = _run(["systemctl", "show", unit, "-p", "ExecStart", "--value"], check=False)
        resolved = (result.stdout or "").strip()
        if f"{RELEASE_ROOT}/{sha}" not in resolved:
            drift.append({"unit": unit, "resolved": resolved[:400]})
    disabled: list[str] = []
    for unit in (*CHAIN_TIMERS, *CHAIN_ENABLED_SERVICES):
        state = _run(["systemctl", "is-enabled", unit], check=False).stdout.strip()
        if state != "enabled":
            disabled.append(f"{unit}={state or 'unknown'}")
    # A timer that is enabled but not loaded fires nothing until the next boot.
    inactive_timers: list[str] = []
    for unit in CHAIN_TIMERS:
        state = _run(["systemctl", "is-active", unit], check=False).stdout.strip()
        if state != "active":
            inactive_timers.append(f"{unit}={state or 'unknown'}")
    return {
        "schema": "confenge.release_pin_verification.v1",
        "release_sha": sha,
        "ok": not drift and not disabled and not inactive_timers,
        "release_drift": drift,
        "not_enabled": disabled,
        "timers_not_active": inactive_timers,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("sha", help="full 40-character release SHA under /opt/extra-consultoria-releases")
    parser.add_argument("--dry-run", action="store_true", help="render and validate without touching the host")
    parser.add_argument("--verify-only", action="store_true", help="only read back the resolved host state")
    args = parser.parse_args(argv)
    try:
        if args.verify_only:
            report = verify(args.sha)
        else:
            report = apply(args.sha, dry_run=args.dry_run)
            if not args.dry_run:
                report = {**report, "verification": verify(args.sha)}
    except (PinError, OSError, subprocess.SubprocessError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    verification = report.get("verification") if isinstance(report, dict) else None
    if isinstance(verification, dict) and verification.get("ok") is False:
        return 2
    if report.get("ok") is False:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
